from pyiceberg.types import *

Exchange_informations = [
    NestedField(1, "order_id", StringType(), required=True),
    NestedField(2, "quote_id", StringType(), required=False),
    NestedField(3, "mobile_no", StringType(), required=False),
    NestedField(4, "name", StringType(), required=False),
    NestedField(5, "imei", StringType(), required=False),
    NestedField(6, "item_code", StringType(), required=False),
    NestedField(7, "status", StringType(), required=False),
    NestedField(8, "customer_id", StringType(), required=False),
    NestedField(9, "customer_info", StringType(), required=False),
    NestedField(10, "category", StringType(), required=False),
    NestedField(11, "brand", StringType(), required=False),
    NestedField(12, "product_info", StringType(), required=False),
    NestedField(13, "exchange_quote_details", StringType(), required=False),
    NestedField(14, "branch_code", StringType(), required=False),
    NestedField(15, "confirm_extra_value", StringType(), required=False),
    NestedField(16, "actual_product_value", StringType(), required=False),
    NestedField(17, "actual_exchange_value", StringType(), required=False),
    NestedField(18, "extra_value_comments", StringType(), required=False),
    NestedField(19, "extra_value", StringType(), required=False),
    NestedField(20, "device_evaluation", StringType(), required=False),
    NestedField(21, "device_images", StringType(), required=False),
    NestedField(22, "created_at", TimestampType(), required=False),
    NestedField(23, "designation", StringType(), required=False),
    NestedField(24, "created_by", StringType(), required=False),
    NestedField(25, "vendor_id", StringType(), required=False),
    NestedField(26, "vendor_name", StringType(), required=False),
    NestedField(27, "device_condition", StringType(), required=False),
]