

pickup_delivery_columns = [
    "pickup_delivery_req_item_id",
    "pickup_delivery_req_id",
    "order_id",
    "sale_order_id",
    "invoice_no",
    "invoice_date",
    "invoice_reff_no",
    "invoice_reff_date",
    "expect_delivery_pickup_dt",
    "customer_status",
    "internal_status",
    "inventory_status",
    "shipment_status",
    "inward_exchange_status",
    "inventory_location_code",
    "docking_area",
    "docking_area_code",
    "type_of_order",
    "item_code",
    "item_name",
    "item_image",
    "item_weight",
    "item_qty",
    "category_code",
    "category_name",
    "inventory_location",
    "inventory_location_branchname",
    "inventory_location_mobileno",
    "order_type",
    "order_line_item_id",
    "picklist_id",
    "picker_id",
    "picker_details",
    "picker_added_dt",
    "manifest_id",
    "manifest_added_dt",
    "shipment_id",
    "driver_code",
    "driver_name",
    "driver_image",
    "driver_contact",
    "assistant_code",
    "assistant_name",
    "assistant_pic",
    "assistant_contact",
    "vehicle_no",
    "vehicle_type",
    "vehicle_name",
    "vehicle_image",
    "order_tag",
    "order_inv_status",
    "tracking_id",
    "tracking_url",
    "permit",
    "courier_name",
    "courier_details",
    "ispickup_active",
    "dimension_length",
    "dimension_height",
    "dimension_width",
    "dimension_units",
    "latitude",
    "longitude",
    "inventory_location_address",
    "status_notification",
    "item_price",
    "item_qty_label",
    "item_dimension",
    "line_itemid",
    "invoice_status",
    "exchange_invo_no",
    "exchange_invo_date",
    "exchange_invoice_url",
    "exchange_collected_amount",
    "brand",
    "capture_do_url",
    "shipment_tracking_id",
    "shipping_label_url",
    "reattempt_count",
    "secondary_assistant_code",
    "secondary_assistant_name",
    "secondary_assistant_pic",
    "secondary_assistant_contact",
    "pickup_label_id",
    "collection_location_type",
    "collection_location_code",
    "collection_location_branchname",
    "collection_location_address",
    "collection_location_mobileno",
    "collection_docking_area",
    "collection_docking_area_code",
    "to_location_email",
    "to_location_mobileno",
    "to_location_address",
    "to_location_pincode",
    "to_location_lat_long",
    "shipment_transfer_info",
    "shipment_type",
    "home_pickup",
    "row_added_dt",
    "row_updated_dt",
    "row_added_by",
    "row_updated_by",
    "goods_received_date",
    "to_location_fullname",
    "courier_code",
    "billing_branch_code",
    "otp_verified_status",
    "item_serial_no",
    "payment_verification",
    "selling_price",
    "vendor_name",
    "vendor_id",
    "vendor_details",
    "is_item_installable",
    "sale_invoice_no",
    "sale_invoice_date",
    "dismantle_label",
    "quote_id",
    "billed_at_branch_name",
    "offer_type",
    "delivery_type",
    "delivery_charge",
    "oms_data_migration_status",
    "dropship_flag",
    "erp_po_createdAt",
    "erp_po_no",
    "seller_order_id",
    "seller_item_code",
    "seller_id",
    "seller_order_createdAt",
    "seller_apob_code",
    "unit_price",
    "discount_price",
]


masterorder_columns = [

    "order_id",
    "sale_order_id",
    "invoice_no",
    "invoice_date",
    "invoice_reff_no",
    "invoice_reff_date",
    "channel",
    "channel_medium",
    "order_status",
    "order_tag",
    "order_inv_status",
    "order_type",
    "delivery_from",
    "delivery_from_branchcode",
    "billing_branch_code",
    "cust_id",
    "cust_primary_email",
    "cust_primary_contact",
    "cust_mobile",
    "customer_address",
    "shipment_address",
    "latitude",
    "longitude",
    "billing_address",
    "payment_details",
    "refund_details",
    "voucher_details",
    "employee_sale_details",
    "order_summary_details",
    "other_details",
    "service_details",
    "invoice_pdf",
    "lineitems",
    "lineitem_status",
    "created_at",
    "created_by",
    "updated_by",
    "updated_at",
    "oms_data_migration_status",
    "cust_id_update",
    "multi_invoice",
    "updated_at_new",
]

orderlineitems_columns =  [
    "line_item_id" ,
    "order_line_item_id" ,
    "master_order_id" ,
    "master_sale_order_id" ,
    "delivery_from" ,
    "customer_status" ,
    "inventory_status" ,
    "internal_status" ,
    "shipping_status" ,
    "category_code" ,
    "category_name" ,
    "item_qty_label" ,
    "exg_invo_no" ,
    "exg_invo_date" ,
    "home_pickup" ,
    "order_inv_status" ,
    "slug" ,
    "product_name" ,
    "model" ,
    "erp_item_code" ,
    "quantity" ,
    "type_of_order" ,
    "product_hsn" ,
    "image" ,
    "options" ,
    "delivery_charges" ,
    "price" ,
    "special_price" ,
    "brand_code" ,
    "brand_name" ,
    "product_policy" ,
    "billed_details" ,
    "delivery_details" ,
    "invoice_details" ,
    "tax_details" ,
    "insurance_details" ,
    "preorder_response" ,
    "seller_details" ,
    "shipment_details" ,
    "return_details" ,
    "return_refund_details" ,
    "return_replace_details" ,
    "return_exchange_details" ,
    "created_at" ,
    "updated_at" ,
    "created_by" ,
    "updated_by" ,
    "serial_no" ,
    "offer_type" ,
    "delivery_type" ,
    "oms_data_migration_status" ,
]

status_events_columns = [
    "status_event_id" ,
    "type" ,
    "channel" ,
    "system" ,
    "medium" ,
    "flow" ,
    "order_id" ,
    "inventory_status" ,
    "shipment_status" ,
    "internal_status" ,
    "customer_status" ,
    "latitude" ,
    "longitude" ,
    "from_location_code" ,
    "to_location_code" ,
    "pickup_delivery_req_item_id" ,
    "intransit_pickup_delivery_req_item_id" ,
    "line_item_id" ,
    "manifest_id" ,
    "shipment_id" ,
    "item_code" ,
    "invoice_no" ,
    "invoice_date" ,
    "exp_delivery_date" ,
    "picklist_id" ,
    "wh_st_empid" ,
    "wh_st_empname" ,
    "driver_code" ,
    "driver_name" ,
    "driver_emp_id" ,
    "driver_contact" ,
    "ass_code" ,
    "ass_name" ,
    "ass_emp_id" ,
    "ass_contact" ,
    "sec_ass_code" ,
    "sec_ass_name" ,
    "sec_emp_id" ,
    "sec_contact" ,
    "vehicle_no" ,
    "vehicle_name" ,
    "docking_area" ,
    "type_of_order" ,
    "cust_name" ,
    "cust_mobile_num" ,
    "imei" ,
    "tracking_id" ,
    "comments" ,
    "courier_name" ,
    "action" ,
    "module_name" ,
    "notification_status" ,
    "order_inv_status" ,
    "additional_info" ,
    "row_added_by" ,
    "row_added_empid" ,
    "row_added_dttm" ,
    "shipment_tracking_id" ,
    "row_updated_dttm" ,
    "oms_data_migration_status" ,
    "updated_at_new" ,
]