users_columns = [
    "id",
    "time_sorted_id",
    "email",
    "email_verified",
    "firstname",
    "lastname",
    "password",
    "role",
    "location_type",
    "warehouse",
    "store",
    "isActive",
    "other_data",
    "picture",
    "branch_code_list",
    "branch_list",
    "mobile_no",
    "created_by",
    "updated_by",
    "created_at",
    "updated_at",
    "createdAt",
    "updatedAt",
    "created_on",
    "updated_on",

]