vehicles_columns = [
    "id",
    "time_sorted_id",
    "type_of_vehicle",
    "truck_name",
    "truck_reg_no",
    "capacity",
    "ratings",
    "is_available",
    "vehicle_from",
    "engine_type",
    "vehicle_image",
    "created_at",
    "updated_at",
    "created_by",
    "updated_by",
    "documents",
    "default_driver_name",
    "default_driver_id",
    "createdAt",
    "updatedAt",
    "branch_code_list",

]