from routers import (
    namespace,
    table,
    filters,
    master_order,
    master_order_w,
    pickup_delivery_items,
    pickup_delivery_items_w,
    status_events,
    orderlineitems,
    bluedart_zone_masters,
    courier_masters,
    drivers,
    exchange_informations,
    exchange_masterorders,
    exchange_masterorders_w,
    exchange_orderlineitems,
    externalcalllogs,
    # orderlineitems_test,
    column,
    schema,
)

all_routers = [
    namespace.router,
    table.router,
    master_order.router,
    master_order_w.router,
    pickup_delivery_items.router,
    pickup_delivery_items_w.router,
    status_events.router,
    orderlineitems.router,
    bluedart_zone_masters.router,
    courier_masters.router,
    drivers.router,
    exchange_informations.router,
    exchange_masterorders.router,
    exchange_masterorders_w.router,
    # orderlineitems_test.router,
    exchange_orderlineitems.router,
    externalcalllogs.router,
    filters.router,
    column.router,
    schema.router,
]