from pyiceberg.types import *

# MasterSchema
MasterSchema = [
    NestedField(1,"order_id",StringType(),required=True),
    NestedField(2, "sale_order_id", StringType(),required=True),
    NestedField(3, "invoice_no", StringType()),
    NestedField(4, "invoice_date", TimestampType()),
    NestedField(5, "invoice_reff_no", StringType()),
    NestedField(6, "invoice_reff_date", StringType()),
    NestedField(7, "channel", StringType()),
    NestedField(8, "channel_medium", StringType()),
    NestedField(9, "order_status", StringType()),
    NestedField(10, "order_tag", StringType()),
    NestedField(11, "order_inv_status", StringType()),
    NestedField(12, "order_type", StringType()),
    NestedField(13, "delivery_from", StringType()),
    NestedField(14, "delivery_from_branchcode", StringType()),
    NestedField(15, "billing_branch_code", StringType()),
    NestedField(16, "cust_id", StringType()),
    NestedField(17, "cust_primary_email", StringType()),
    NestedField(18, "cust_primary_contact", StringType()),
    NestedField(19, "cust_mobile", StringType()),
    NestedField(20, "customer_address", StringType()),
    NestedField(21, "shipment_address", StringType()),
    NestedField(22, "latitude", DoubleType()),
    NestedField(23, "longitude", DoubleType()),
    NestedField(24, "billing_address", StringType()),
    NestedField(25, "payment_details", StringType()),
    NestedField(26, "refund_details", StringType()),
    NestedField(27, "voucher_details", StringType()),
    NestedField(28, "employee_sale_details", StringType()),
    NestedField(29, "order_summary_details", StringType()),
    NestedField(30, "other_details", StringType()),
    NestedField(31, "service_details", StringType()),
    NestedField(32, "invoice_pdf", StringType()),
    NestedField(33, "lineitems", StringType()),
    NestedField(34, "lineitem_status", StringType()),
    NestedField(35, "created_at", TimestampType()),
    NestedField(36, "created_by", StringType()),
    NestedField(37, "updated_by", StringType()),
    NestedField(38, "updated_at", TimestampType()),
    NestedField(39, "oms_data_migration_status", IntegerType()),
    NestedField(40, "cust_id_update", IntegerType()),
    NestedField(41, "multi_invoice", StringType()),
    NestedField(42, "updated_at_new", TimestampType())
]

# Pickup_delivery_items
# Pickup_delivery_items = [
#     NestedField(1, "pickup_delivery_req_item_id", StringType()),
#     NestedField(2, "pickup_delivery_req_id", StringType()),
#     NestedField(3, "order_id", StringType()),
#     NestedField(4, "sale_order_id", StringType()),
#     NestedField(5, "invoice_no", StringType()),
#     NestedField(6, "invoice_date", TimestampType()),
#     NestedField(7, "invoice_reff_no", StringType()),
#     NestedField(8, "invoice_reff_date", StringType()),
#     NestedField(9, "expect_delivery_pickup_dt", TimestampType()),
#     NestedField(10, "customer_status", StringType()),
#     NestedField(11, "internal_status", StringType()),
#     NestedField(12, "inventory_status", StringType()),
#     NestedField(13, "shipment_status", StringType()),
#     NestedField(14, "inward_exchange_status", StringType()),
#     NestedField(15, "inventory_location_code", StringType()),
#     NestedField(16, "docking_area", StringType()),
#     NestedField(17, "docking_area_code", StringType()),
#     NestedField(18, "type_of_order", StringType()),
#     NestedField(19, "item_code", StringType()),
#     NestedField(20, "item_name", StringType()),
#     NestedField(21, "item_image", StringType()),
#     NestedField(22, "item_weight", StringType()),
#     NestedField(23, "item_qty", IntegerType()),
#     NestedField(24, "category_code", StringType()),
#     NestedField(25, "category_name", StringType()),
#     NestedField(26, "inventory_location", StringType()),
#     NestedField(27, "inventory_location_branchname", StringType()),
#     NestedField(28, "inventory_location_mobileno", StringType()),
#     NestedField(29, "order_type", StringType()),
#     NestedField(30, "order_line_item_id", StringType()),
#     NestedField(31, "picklist_id", StringType()),
#     NestedField(32, "picker_id", StringType()),
#     NestedField(33, "picker_details", StringType()),
#     NestedField(34, "picker_added_dt", TimestampType()),
#     NestedField(35, "manifest_id", StringType()),
#     NestedField(36, "manifest_added_dt", TimestampType()),
#     NestedField(37, "shipment_id", StringType()),
#     NestedField(38, "driver_code", StringType()),
#     NestedField(39, "driver_name", StringType()),
#     NestedField(40, "driver_image", StringType()),
#     NestedField(41, "driver_contact", StringType()),
#     NestedField(42, "assistant_code", StringType()),
#     NestedField(43, "assistant_name", StringType()),
#     NestedField(44, "assistant_pic", StringType()),
#     NestedField(45, "assistant_contact", StringType()),
#     NestedField(46, "vehicle_no", StringType()),
#     NestedField(47, "vehicle_type", StringType()),
#     NestedField(48, "vehicle_name", StringType()),
#     NestedField(49, "vehicle_image", StringType()),
#     NestedField(50, "order_tag", StringType()),
#     NestedField(51, "order_inv_status", StringType()),
#     NestedField(52, "tracking_id", StringType()),
#     NestedField(53, "tracking_url", StringType()),
#     NestedField(54, "permit", StringType()),
#     NestedField(55, "courier_name", StringType()),
#     NestedField(56, "courier_details", StringType()),
#     NestedField(57, "ispickup_active", IntegerType()),
#     NestedField(58, "dimension_length", IntegerType()),
#     NestedField(59, "dimension_height", IntegerType()),
#     NestedField(60, "dimension_width", IntegerType()),
#     NestedField(61, "dimension_units", StringType()),
#     # NestedField(62, "latitude",FloatType()) ,
#     # NestedField(63, "longitude", FloatType()),
#     NestedField(62, "latitude", DoubleType(), required=False),
#     NestedField(63, "longitude", DoubleType(), required=False),
#     NestedField(64, "inventory_location_address", StringType()),
#     NestedField(65, "status_notification", StringType()),
#     NestedField(66, "item_price", StringType()),
#     NestedField(67, "item_qty_label", StringType()),
#     NestedField(68, "item_dimension", StringType()),
#     NestedField(69, "line_itemid", StringType()),
#     NestedField(70, "invoice_status", StringType()),
#     NestedField(71, "exchange_invo_no", StringType()),
#     NestedField(72, "exchange_invo_date", TimestampType()),
#     NestedField(73, "exchange_invoice_url", StringType()),
#     NestedField(74, "exchange_collected_amount", StringType()),
#     NestedField(75, "brand", StringType()),
#     NestedField(76, "capture_do_url", StringType()),
#     NestedField(77, "shipment_tracking_id", StringType()),
#     NestedField(78, "shipping_label_url", StringType()),
#     NestedField(79, "reattempt_count", IntegerType()),
#     NestedField(80, "secondary_assistant_code", StringType()),
#     NestedField(81, "secondary_assistant_name", StringType()),
#     NestedField(82, "secondary_assistant_pic", StringType()),
#     NestedField(83, "secondary_assistant_contact", StringType()),
#     NestedField(84, "pickup_label_id", StringType()),
#     NestedField(85, "collection_location_type", StringType()),
#     NestedField(86, "collection_location_code", StringType()),
#     NestedField(87, "collection_location_branchname", StringType()),
#     NestedField(88, "collection_location_address", StringType()),
#     NestedField(89, "collection_location_mobileno", StringType()),
#     NestedField(90, "collection_docking_area", StringType()),
#     NestedField(91, "collection_docking_area_code", StringType()),
#     NestedField(92, "to_location_email", StringType()),
#     NestedField(93, "to_location_mobileno", StringType()),
#     NestedField(94, "to_location_address", StringType()),
#     NestedField(95, "to_location_pincode", IntegerType()),
#     NestedField(96, "to_location_lat_long", StringType()),
#     NestedField(97, "shipment_transfer_info", StringType()),
#     NestedField(98, "shipment_type", StringType()),
#     NestedField(99, "home_pickup", StringType()),
#     NestedField(100, "row_added_dt", TimestampType()),
#     NestedField(101, "row_updated_dt", TimestampType()),
#     NestedField(102, "row_added_by", StringType()),
#     NestedField(103, "row_updated_by", StringType()),
#     NestedField(104, "goods_received_date", TimestampType()),
#     NestedField(105, "to_location_fullname", StringType()),
#     NestedField(106, "courier_code", StringType()),
#     NestedField(107, "billing_branch_code", StringType()),
#     NestedField(108, "otp_verified_status", IntegerType()),
#     NestedField(109, "item_serial_no", StringType()),
#     NestedField(110, "payment_verification", IntegerType()),
#     NestedField(111, "selling_price", StringType()),
#     NestedField(112, "vendor_name", StringType()),
#     NestedField(113, "vendor_id", StringType()),
#     NestedField(114, "vendor_details", StringType()),
#     NestedField(115, "is_item_installable", StringType()),
#     NestedField(116, "sale_invoice_no", StringType()),
#     NestedField(117, "sale_invoice_date", DateType()),
#     NestedField(118, "dismantle_label", StringType()),
#     NestedField(119, "quote_id", StringType()),
#     NestedField(120, "billed_at_branch_name", StringType()),
#     NestedField(121, "offer_type", StringType()),
#     NestedField(122, "delivery_type", StringType()),
#     NestedField(123, "delivery_charge", IntegerType()),
#     NestedField(124, "oms_data_migration_status", IntegerType()),
#     NestedField(125, "dropship_flag", IntegerType()),
#     NestedField(126, "erp_po_createdAt", StringType()),
#     NestedField(127, "erp_po_no", StringType()),
#     NestedField(128, "seller_order_id", StringType()),
#     NestedField(129, "seller_item_code", StringType()),
#     NestedField(130, "seller_id", StringType()),
#     NestedField(131, "seller_order_createdAt", StringType()),
#     NestedField(132, "seller_apob_code", StringType()),
#     NestedField(133, "unit_price", StringType()),
#     NestedField(134, "discount_price", StringType()),
#     NestedField(135, "plant", StringType()),
#     NestedField(136, "seller_branch_code", StringType()),
#     NestedField(137, "tracking_details", StringType()),
#     NestedField(138, "invoiced_item_detail", StringType()),
#     NestedField(139, "invoice_url", StringType()),
#     NestedField(140, "updated_at_new", TimestampType()),
# ]

drivers_dob_error_columns = [
    # ---------------- PRIMARY / CORE ----------------
    NestedField(1, "id", StringType(), required=True),
    NestedField(2, "time_sorted_id", StringType(), required=True),
    NestedField(3, "type_of_work", StringType(), required=True),
    NestedField(4, "employee_from", StringType(), required=True),
    NestedField(5, "work_type", StringType(), required=True),
    NestedField(6, "firstname", StringType(), required=True),
    NestedField(7, "lastname", StringType(), required=True),
    NestedField(8, "dob", TimestampType(), required=True),

    # ---------------- CONTACT ----------------
    NestedField(9, "primary_contact", StringType(), required=True),
    NestedField(10, "secondary_contact", StringType(), required=False),

    # ---------------- ADDRESS ----------------
    NestedField(11, "address_line1", StringType(), required=True),
    NestedField(12, "address_line2", StringType(), required=False),
    NestedField(13, "city", StringType(), required=True),
    NestedField(14, "state", StringType(), required=True),
    NestedField(15, "pincode", IntegerType(), required=True),
    NestedField(16, "area", StringType(), required=False),
    NestedField(17, "country", StringType(), required=True),

    # ---------------- PERSONAL ----------------
    NestedField(18, "gender", StringType(), required=True),
    NestedField(19, "profile_pic_url", StringType(), required=False),

    # ---------------- STATUS ----------------
    NestedField(20, "isActive", IntegerType(), required=False),
    NestedField(21, "remarks", StringType(), required=False),
    NestedField(22, "ratings", StringType(), required=False),
    NestedField(23, "approval_status", StringType(), required=False),

    # ---------------- IDENTITY DOCS ----------------
    NestedField(24, "driving_license_num", StringType(), required=True),
    NestedField(25, "driving_license_url", StringType(), required=True),
    NestedField(26, "driving_license_expiry", TimestampType(), required=False),

    NestedField(27, "aadhar_card_num", StringType(), required=True),
    NestedField(28, "aadhar_card_url", StringType(), required=True),

    NestedField(29, "voter_id_num", StringType(), required=False),
    NestedField(30, "voter_id_url", StringType(), required=False),

    NestedField(31, "ration_card_num", StringType(), required=False),
    NestedField(32, "ration_card_url", StringType(), required=False),

    NestedField(33, "pancard_num", StringType(), required=False),
    NestedField(34, "pancard_url", StringType(), required=False),

    # ---------------- AUDIT ----------------
    NestedField(35, "created_on", TimestampType(), required=True),
    NestedField(36, "updated_on", TimestampType(), required=False),
    NestedField(37, "created_at", TimestampType(), required=True),
    NestedField(38, "updated_at", TimestampType(), required=False),
    NestedField(39, "createdAt", TimestampType(), required=True),
    NestedField(40, "updatedAt", TimestampType(), required=False),
    NestedField(41, "created_by", StringType(), required=False),
    NestedField(42, "updated_by", StringType(), required=False),

    # ---------------- JSON / META ----------------
    NestedField(43, "branch_code_list", StringType(), required=False),
    NestedField(44, "branchcode", StringType(), required=False),

    # ---------------- EMP ----------------
    NestedField(45, "emp_id", StringType(), required=False),
]

Pickup_delivery_items = [
    NestedField(1, "pickup_delivery_req_item_id", StringType(), required=False),
    NestedField(2, "pickup_delivery_req_id", StringType(), required=False),
    NestedField(3, "order_id", StringType(), required=False),
    NestedField(4, "sale_order_id", StringType(), required=False),
    NestedField(5, "invoice_no", StringType()),
    NestedField(6, "invoice_date", TimestampType()),
    NestedField(7, "invoice_reff_no", StringType()),
    NestedField(8, "invoice_reff_date", StringType()),
    NestedField(9, "expect_delivery_pickup_dt", TimestampType(), required=False),

    NestedField(10, "customer_status", StringType()),
    NestedField(11, "internal_status", StringType(), required=False),
    NestedField(12, "inventory_status", StringType(), required=False),
    NestedField(13, "shipment_status", StringType(), required=False),
    NestedField(14, "inward_exchange_status", StringType()),

    NestedField(15, "inventory_location_code", StringType(), required=False),
    NestedField(16, "docking_area", StringType()),
    NestedField(17, "docking_area_code", StringType()),
    NestedField(18, "type_of_order", StringType()),

    NestedField(19, "item_code", StringType(), required=False),
    NestedField(20, "item_name", StringType(), required=False),
    NestedField(21, "item_image", StringType(), required=False),
    NestedField(22, "item_weight", StringType(), required=False),
    NestedField(23, "item_qty", StringType(), required=False),

    NestedField(24, "category_code", StringType()),
    NestedField(25, "category_name", StringType()),
    NestedField(26, "inventory_location", StringType(), required=False),
    NestedField(27, "inventory_location_branchname", StringType()),
    NestedField(28, "inventory_location_mobileno", StringType()),

    NestedField(29, "order_type", StringType()),
    NestedField(30, "order_line_item_id", StringType(), required=False),
    NestedField(31, "picklist_id", StringType(), required=False),
    NestedField(32, "picker_id", StringType(), required=False),
    NestedField(33, "picker_details", StringType()),
    NestedField(34, "picker_added_dt", TimestampType()),

    NestedField(35, "manifest_id", StringType(), required=False),
    NestedField(36, "manifest_added_dt", TimestampType()),
    NestedField(37, "shipment_id", StringType(), required=False),

    NestedField(38, "driver_code", StringType()),
    NestedField(39, "driver_name", StringType(), required=False),
    NestedField(40, "driver_image", StringType()),
    NestedField(41, "driver_contact", StringType()),

    NestedField(42, "assistant_code", StringType()),
    NestedField(43, "assistant_name", StringType()),
    NestedField(44, "assistant_pic", StringType()),
    NestedField(45, "assistant_contact", StringType()),

    NestedField(46, "vehicle_no", StringType()),
    NestedField(47, "vehicle_type", StringType()),
    NestedField(48, "vehicle_name", StringType()),
    NestedField(49, "vehicle_image", StringType()),

    NestedField(50, "order_tag", StringType()),
    NestedField(51, "order_inv_status", StringType()),
    NestedField(52, "tracking_id", StringType()),
    NestedField(53, "tracking_url", StringType()),
    NestedField(54, "permit", StringType(), required=False),

    NestedField(55, "courier_name", StringType()),
    NestedField(56, "courier_details", StringType()),
    NestedField(57, "ispickup_active", BooleanType(), required=False),

    NestedField(58, "dimension_length", StringType()),
    NestedField(59, "dimension_height", StringType()),
    NestedField(60, "dimension_width", StringType()),
    NestedField(61, "dimension_units", StringType()),

    NestedField(62, "latitude", StringType()),
    NestedField(63, "longitude", StringType()),

    NestedField(64, "inventory_location_address", StringType()),
    NestedField(65, "status_notification", StringType()),

    NestedField(66, "item_price", StringType()),
    NestedField(67, "item_qty_label", StringType()),
    NestedField(68, "item_dimension", StringType()),
    NestedField(69, "line_itemid", StringType()),

    NestedField(70, "invoice_status", StringType()),
    NestedField(71, "exchange_invo_no", StringType()),
    NestedField(72, "exchange_invo_date", TimestampType()),
    NestedField(73, "exchange_invoice_url", StringType()),
    NestedField(74, "exchange_collected_amount", StringType()),

    NestedField(75, "brand", StringType()),
    NestedField(76, "capture_do_url", StringType()),
    NestedField(77, "shipment_tracking_id", StringType()),
    NestedField(78, "shipping_label_url", StringType()),
    NestedField(79, "reattempt_count", StringType()),

    NestedField(80, "secondary_assistant_code", StringType()),
    NestedField(81, "secondary_assistant_name", StringType()),
    NestedField(82, "secondary_assistant_pic", StringType()),
    NestedField(83, "secondary_assistant_contact", StringType()),

    NestedField(84, "pickup_label_id", StringType()),

    NestedField(85, "collection_location_type", StringType()),
    NestedField(86, "collection_location_code", StringType()),
    NestedField(87, "collection_location_branchname", StringType()),
    NestedField(88, "collection_location_address", StringType()),
    NestedField(89, "collection_location_mobileno", StringType()),
    NestedField(90, "collection_docking_area", StringType()),
    NestedField(91, "collection_docking_area_code", StringType()),

    NestedField(92, "to_location_email", StringType()),
    NestedField(93, "to_location_mobileno", StringType()),
    NestedField(94, "to_location_address", StringType()),
    NestedField(95, "to_location_pincode", StringType(), required=False),
    NestedField(96, "to_location_lat_long", StringType()),

    NestedField(97, "shipment_transfer_info", StringType()),
    NestedField(98, "shipment_type", StringType()),
    NestedField(99, "home_pickup", StringType()),

    NestedField(100, "row_added_dt", TimestampType(), required=False),
    NestedField(101, "row_updated_dt", TimestampType()),
    NestedField(102, "row_added_by", StringType(), required=False),
    NestedField(103, "row_updated_by", StringType(), required=False),

    NestedField(104, "goods_received_date", TimestampType()),
    NestedField(105, "to_location_fullname", StringType()),
    NestedField(106, "courier_code", StringType()),
    NestedField(107, "billing_branch_code", StringType()),

    NestedField(108, "otp_verified_status", BooleanType()),
    NestedField(109, "item_serial_no", StringType()),
    NestedField(110, "payment_verification", BooleanType()),

    NestedField(111, "selling_price", StringType()),
    NestedField(112, "vendor_name", StringType()),
    NestedField(113, "vendor_id", StringType()),
    NestedField(114, "vendor_details", StringType()),

    NestedField(115, "sale_invoice_no", StringType()),
    NestedField(116, "sale_invoice_date", StringType()),
    NestedField(117, "dismantle_label", StringType()),

    NestedField(118, "is_item_installable", StringType(), required=False),

    NestedField(119, "quote_id", StringType()),
    NestedField(120, "billed_at_branch_name", StringType()),
    NestedField(121, "offer_type", StringType()),
    NestedField(122, "delivery_type", StringType()),

    NestedField(123, "delivery_charge", StringType()),
    NestedField(124, "dropship_flag", BooleanType()),
    NestedField(125, "erp_po_createdAt", StringType()),
    NestedField(126, "erp_po_no", StringType()),

    NestedField(127, "seller_order_id", StringType()),
    NestedField(128, "seller_item_code", StringType()),
    NestedField(129, "seller_id", StringType()),
    NestedField(130, "seller_order_createdAt", StringType()),
    NestedField(131, "seller_apob_code", StringType()),

    NestedField(132, "unit_price", StringType()),
    NestedField(133, "discount_price", StringType()),
    NestedField(134, "plant", StringType()),
    NestedField(135, "seller_branch_code", StringType()),

    NestedField(136, "tracking_details", StringType()),
    NestedField(137, "invoiced_item_detail", StringType()),
    NestedField(138, "invoice_url", StringType()),

    NestedField(139, "preorder", BooleanType()),
    NestedField(140, "mapping_domain", StringType()),
    NestedField(141, "payment_email", StringType()),
    NestedField(142, "customer_name", StringType()),
    NestedField(143, "customer_mobile", StringType()),
    NestedField(144, "payment_code", StringType()),
    NestedField(145, "payment_status", StringType()),

    NestedField(146, "delivery_from_branch_details", StringType()),
    NestedField(147, "delivery_from_branch_code", StringType()),
    NestedField(148, "adld_charges", StringType()),
    NestedField(149, "ew_charges", StringType()),
    NestedField(150, "reject_remarks", StringType()),

    NestedField(151, "billing_from_branch_details", StringType()),
    NestedField(152, "billing_from_branch_code", StringType()),
    NestedField(153, "billing_gst_no", StringType()),
    NestedField(154, "shipping_pincode", StringType()),
    NestedField(155, "shipping_state", StringType()),
    NestedField(156, "customer_email", StringType()),
]

Pickup_delivery_items_w = [

    NestedField(1, "pickup_delivery_req_item_id", StringType(), required=False),
    NestedField(2, "pickup_delivery_req_id", StringType(), required=False),
    NestedField(3, "order_id", StringType(), required=False),
    NestedField(4, "sale_order_id", StringType(), required=False),
    NestedField(5, "invoice_no", StringType()),
    NestedField(6, "invoice_date", TimestampType()),
    NestedField(7, "invoice_reff_no", StringType()),
    NestedField(8, "invoice_reff_date", StringType()),
    NestedField(9, "expect_delivery_pickup_dt", TimestampType(), required=False),

    NestedField(10, "customer_status", StringType()),
    NestedField(11, "internal_status", StringType(), required=False),
    NestedField(12, "inventory_status", StringType(), required=False),
    NestedField(13, "shipment_status", StringType(), required=False),
    NestedField(14, "inward_exchange_status", StringType()),

    NestedField(15, "inventory_location_code", StringType(), required=False),
    NestedField(16, "docking_area", StringType()),
    NestedField(17, "docking_area_code", StringType()),
    NestedField(18, "type_of_order", StringType()),

    NestedField(19, "item_code", StringType(), required=False),
    NestedField(20, "item_name", StringType(), required=False),
    NestedField(21, "item_image", StringType(), required=False),
    NestedField(22, "item_weight", StringType(), required=False),
    NestedField(23, "item_qty", StringType(), required=False),

    NestedField(24, "category_code", StringType()),
    NestedField(25, "category_name", StringType()),
    NestedField(26, "inventory_location", StringType(), required=False),
    NestedField(27, "inventory_location_branchname", StringType()),
    NestedField(28, "inventory_location_mobileno", StringType()),

    NestedField(29, "order_type", StringType()),
    NestedField(30, "order_line_item_id", StringType(), required=False),
    NestedField(31, "picklist_id", StringType(), required=False),
    NestedField(32, "picker_id", StringType(), required=False),
    NestedField(33, "picker_details", StringType()),
    NestedField(34, "picker_added_dt", TimestampType()),

    NestedField(35, "manifest_id", StringType(), required=False),
    NestedField(36, "manifest_added_dt", TimestampType()),
    NestedField(37, "shipment_id", StringType(), required=False),

    NestedField(38, "driver_code", StringType()),
    NestedField(39, "driver_name", StringType(), required=False),
    NestedField(40, "driver_image", StringType()),
    NestedField(41, "driver_contact", StringType()),

    NestedField(42, "assistant_code", StringType()),
    NestedField(43, "assistant_name", StringType()),
    NestedField(44, "assistant_pic", StringType()),
    NestedField(45, "assistant_contact", StringType()),

    NestedField(46, "vehicle_no", StringType()),
    NestedField(47, "vehicle_type", StringType()),
    NestedField(48, "vehicle_name", StringType()),
    NestedField(49, "vehicle_image", StringType()),

    NestedField(50, "order_tag", StringType()),
    NestedField(51, "order_inv_status", StringType()),
    NestedField(52, "tracking_id", StringType()),
    NestedField(53, "tracking_url", StringType()),
    NestedField(54, "permit", StringType(), required=False),

    NestedField(55, "courier_name", StringType()),
    NestedField(56, "courier_details", StringType()),
    NestedField(57, "ispickup_active", BooleanType(), required=False),

    NestedField(58, "dimension_length", StringType()),
    NestedField(59, "dimension_height", StringType()),
    NestedField(60, "dimension_width", StringType()),
    NestedField(61, "dimension_units", StringType()),

    NestedField(62, "latitude", StringType()),
    NestedField(63, "longitude", StringType()),

    NestedField(64, "inventory_location_address", StringType()),
    NestedField(65, "status_notification", StringType()),

    NestedField(66, "item_price", StringType()),
    NestedField(67, "item_qty_label", StringType()),
    NestedField(68, "item_dimension", StringType()),
    NestedField(69, "line_itemid", StringType()),

    NestedField(70, "invoice_status", StringType()),
    NestedField(71, "exchange_invo_no", StringType()),
    NestedField(72, "exchange_invo_date", TimestampType()),
    NestedField(73, "exchange_invoice_url", StringType()),
    NestedField(74, "exchange_collected_amount", StringType()),

    NestedField(75, "brand", StringType()),
    NestedField(76, "capture_do_url", StringType()),
    NestedField(77, "shipment_tracking_id", StringType()),
    NestedField(78, "shipping_label_url", StringType()),
    NestedField(79, "reattempt_count", StringType()),

    NestedField(80, "secondary_assistant_code", StringType()),
    NestedField(81, "secondary_assistant_name", StringType()),
    NestedField(82, "secondary_assistant_pic", StringType()),
    NestedField(83, "secondary_assistant_contact", StringType()),

    NestedField(84, "pickup_label_id", StringType()),
    NestedField(85, "collection_location_type", StringType()),
    NestedField(86, "collection_location_code", StringType()),
    NestedField(87, "collection_location_branchname", StringType()),
    NestedField(88, "collection_location_address", StringType()),
    NestedField(89, "collection_location_mobileno", StringType()),
    NestedField(90, "collection_docking_area", StringType()),
    NestedField(91, "collection_docking_area_code", StringType()),

    NestedField(92, "to_location_email", StringType()),
    NestedField(93, "to_location_mobileno", StringType()),
    NestedField(94, "to_location_address", StringType()),
    NestedField(95, "to_location_pincode", StringType(), required=False),
    NestedField(96, "to_location_lat_long", StringType()),

    NestedField(97, "shipment_transfer_info", StringType()),
    NestedField(98, "shipment_type", StringType()),
    NestedField(99, "home_pickup", StringType()),

    NestedField(100, "row_added_dt", TimestampType(), required=False),
    NestedField(101, "row_updated_dt", TimestampType()),
    NestedField(102, "row_added_by", StringType(), required=False),
    NestedField(103, "row_updated_by", StringType(), required=False),

    NestedField(104, "goods_received_date", TimestampType()),
    NestedField(105, "to_location_fullname", StringType()),
    NestedField(106, "courier_code", StringType()),
    NestedField(107, "billing_branch_code", StringType()),

    NestedField(108, "otp_verified_status", BooleanType()),
    NestedField(109, "item_serial_no", StringType()),
    NestedField(110, "payment_verification", BooleanType()),

    NestedField(111, "selling_price", StringType()),
    NestedField(112, "vendor_name", StringType()),
    NestedField(113, "vendor_id", StringType()),
    NestedField(114, "vendor_details", StringType()),

    NestedField(115, "sale_invoice_no", StringType()),
    NestedField(116, "sale_invoice_date", StringType()),
    NestedField(117, "dismantle_label", StringType()),

    NestedField(118, "is_item_installable", StringType(), required=False),

    NestedField(119, "quote_id", StringType()),
    NestedField(120, "billed_at_branch_name", StringType()),
    NestedField(121, "offer_type", StringType()),
    NestedField(122, "delivery_type", StringType()),

    NestedField(123, "dropship_flag", BooleanType()),
    NestedField(124, "erp_po_createdAt", StringType()),
    NestedField(125, "erp_po_no", StringType()),
    NestedField(126, "seller_order_id", StringType()),
    NestedField(127, "seller_item_code", StringType()),
    NestedField(128, "seller_id", StringType()),
    NestedField(129, "seller_order_createdAt", StringType()),
    NestedField(130, "seller_apob_code", StringType()),

    NestedField(131, "unit_price", StringType()),
    NestedField(132, "discount_price", StringType()),
    NestedField(133, "plant", StringType()),
    NestedField(134, "seller_branch_code", StringType()),

    NestedField(135, "tracking_details", StringType()),
    NestedField(136, "invoiced_item_detail", StringType()),
    NestedField(137, "invoice_url", StringType()),

    NestedField(138, "delivery_charge", StringType()),
    NestedField(139, "billing_from_branch_code", StringType()),
    NestedField(140, "billing_from_branch_details", StringType()),
    NestedField(141, "billing_gst_no", StringType()),

    NestedField(142, "shipping_pincode", StringType()),
    NestedField(143, "shipping_state", StringType()),
    NestedField(144, "customer_email", StringType()),
    NestedField(145, "preorder", BooleanType()),
    NestedField(146, "mapping_domain", StringType()),
    NestedField(147, "payment_email", StringType()),
    NestedField(148, "customer_name", StringType()),
    NestedField(149, "customer_mobile", StringType()),
    NestedField(150, "payment_code", StringType()),

    NestedField(151, "payment_status", StringType()),
    NestedField(152, "delivery_from_branch_details", StringType()),
    NestedField(153, "delivery_from_branch_code", StringType()),
    NestedField(154, "adld_charges", StringType()),
    NestedField(155, "ew_charges", StringType()),
    NestedField(156, "reject_remarks", StringType()),
]
# Status_event
Status_event = [
    NestedField(1,"status_event_id",StringType()),
    NestedField(2,"type",StringType()),
    NestedField(3,"channel",StringType()),
    NestedField(4,"system",StringType()),
    NestedField(5,"medium",StringType()),
    NestedField(6,"flow",StringType()),
    NestedField(7,"order_id",StringType()),
    NestedField(8,"inventory_status",StringType()),
    NestedField(9,"shipment_status",StringType()),
    NestedField(10,"internal_status",StringType()),
    NestedField(11,"customer_status",StringType()),
    # NestedField(12,"latitude",FloatType()),
    # NestedField(13,"longitude",FloatType()),
    NestedField(12,"latitude",DoubleType()),
    NestedField(13,"longitude",DoubleType()),
    NestedField(14,"from_location_code",StringType()),
    NestedField(15,"to_location_code",StringType()),
    NestedField(16,"pickup_delivery_req_item_id",StringType()),
    NestedField(17,"intransit_pickup_delivery_req_item_id",StringType()),
    NestedField(18,"line_item_id",StringType()),
    NestedField(19,"manifest_id",StringType()),
    NestedField(20,"shipment_id",StringType()),
    NestedField(21,"item_code",StringType()),
    NestedField(22,"invoice_no",StringType()),
    NestedField(23,"invoice_date",TimestampType()),
    NestedField(24,"exp_delivery_date",TimestampType()),
    NestedField(25,"picklist_id",StringType()),
    NestedField(26,"wh_st_empid",StringType()),
    NestedField(27,"wh_st_empname", StringType()),
    NestedField(28,"driver_code",StringType()),
    NestedField(29,"driver_name",StringType()),
    NestedField(30,"driver_emp_id",StringType()),
    NestedField(31,"driver_contact",StringType()),
    NestedField(32,"ass_code",StringType()),
    NestedField(33,"ass_name",StringType()),
    NestedField(34,"ass_emp_id",StringType()),
    NestedField(35,"ass_contact",StringType()),
    NestedField(36,"sec_ass_code",StringType()),
    NestedField(37,"sec_ass_name",StringType()),
    NestedField(38,"sec_emp_id",StringType()),
    NestedField(39,"sec_contact",StringType()),
    NestedField(40,"vehicle_no",StringType()),
    NestedField(41,"vehicle_name",StringType()),
    NestedField(42,"docking_area",StringType()),
    NestedField(43,"type_of_order",StringType()),
    NestedField(44,"cust_name",StringType()),
    NestedField(45,"cust_mobile_num",StringType()),
    NestedField(46,"imei",StringType()),
    NestedField(47,"tracking_id",StringType()),
    NestedField(48,"comments",StringType()),
    NestedField(49,"courier_name",StringType()),
    NestedField(50,"action",StringType()),
    NestedField(51,"module_name",StringType()),
    NestedField(52,"notification_status",StringType()),
    NestedField(53,"order_inv_status",StringType()),
    NestedField(54,"additional_info",StringType()),
    NestedField(55,"row_added_by",StringType()),
    NestedField(56,"row_added_empid",StringType()),
    NestedField(57,"row_added_dttm",TimestampType()),
    NestedField(58,"shipment_tracking_id",StringType()),
    NestedField(59,"row_updated_dttm",TimestampType()),
    NestedField(60,"oms_data_migration_status",IntegerType()),
    # NestedField(61,"updated_at_new",TimestampType()),

]

# OrderLineItems
OrderLineItems = [
    NestedField(1,"line_item_id",StringType()),
    NestedField(2,"order_line_item_id",StringType()),
    NestedField(3,"master_order_id",StringType()),
    NestedField(4,"master_sale_order_id",StringType()),
    NestedField(5,"delivery_from",StringType()),
    NestedField(6,"customer_status",StringType()),
    NestedField(7,"inventory_status",StringType()),
    NestedField(8,"internal_status",StringType()),
    NestedField(9,"shipping_status",StringType()),
    NestedField(10,"category_code",StringType()),
    NestedField(11,"category_name",StringType()),
    NestedField(12,"item_qty_label",StringType()),
    NestedField(13,"exg_invo_no",StringType()),
    NestedField(14,"exg_invo_date",StringType()),
    NestedField(15,"home_pickup",StringType()),
    NestedField(16,"order_inv_status",StringType()),
    NestedField(17,"slug",StringType()),
    NestedField(18,"product_name",StringType()),
    NestedField(19,"model",StringType()),
    NestedField(20,"erp_item_code",StringType()),
    NestedField(21,"quantity",IntegerType()),
    NestedField(22,"type_of_order",StringType()),
    NestedField(23,"product_hsn",StringType()),
    NestedField(24,"image",StringType()),
    NestedField(25,"options",StringType()),
    NestedField(26,"delivery_charges",StringType()),
    NestedField(27,"price",StringType()),
    NestedField(28,"special_price",IntegerType()),
    NestedField(29,"brand_code",StringType()),
    NestedField(30,"brand_name",StringType()),
    NestedField(31,"product_policy",StringType()),
    NestedField(32,"billed_details",StringType()),
    NestedField(33,"delivery_details",StringType()),
    NestedField(34,"invoice_details",StringType()),
    NestedField(35,"tax_details",StringType()),
    NestedField(36,"insurance_details",StringType()),
    NestedField(37,"preorder_response",StringType()),
    NestedField(38,"seller_details",StringType()),
    NestedField(39,"shipment_details",StringType()),
    NestedField(40,"return_details",StringType()),
    NestedField(41,"return_refund_details",StringType()),
    NestedField(42,"return_replace_details",StringType()),
    NestedField(43,"return_exchange_details",StringType()),
    NestedField(44,"created_at",TimestampType()),
    NestedField(45,"updated_at",TimestampType()),
    NestedField(46,"created_by",StringType()),
    NestedField(47,"updated_by",StringType()),
    NestedField(48,"serial_no",StringType()),
    NestedField(49,"offer_type",StringType()),
    NestedField(50,"delivery_type",StringType()),
    NestedField(51,"oms_data_migration_status",IntegerType()),
    
]

# OrderLineItems_test
OrderLineItems_test = [
    NestedField(1, "line_item_id", StringType()),
    NestedField(2, "order_line_item_id", StringType()),
    NestedField(3, "master_order_id", StringType()),
    NestedField(4, "master_sale_order_id", StringType()),
    NestedField(5, "delivery_from", StringType()),
    NestedField(6,"created_at",TimestampType()),
]

# Bluedart_zone_masters
Bluedart_zone_masters = [
    NestedField(1, "id", LongType(), required=True),
    NestedField(2, "cpincode", StringType()),
    NestedField(3, "cpindesc", StringType()),
    NestedField(4, "city", StringType()),
    NestedField(5, "bdsc", StringType()),
    NestedField(6, "state", StringType()),
    NestedField(7, "carea", StringType()),
    NestedField(8, "cecomzn", StringType()),
    NestedField(9, "region", StringType()),
    NestedField(10, "created_at", TimestampType()),
    NestedField(11, "updated_at", TimestampType()),
    NestedField(12, "created_by", StringType(), required=False),
    NestedField(13, "updated_by", StringType(), required=False),
    NestedField(14, "cscrcd", StringType(), required=False),
]

# Courier_masters
Courier_masters = [
    NestedField(1, "code", StringType(), required=True),
    NestedField(2, "name", StringType(), required=False),
    NestedField(3, "type", StringType(), required=False),
    NestedField(4, "isactive", BooleanType(), required=False),
    NestedField(5, "image", StringType(), required=False),
    NestedField(6, "description", StringType(), required=False),
    NestedField(7, "created_at", TimestampType(), required=True),
    NestedField(8, "updated_at", TimestampType(), required=False),
    NestedField(9, "created_by", StringType(), required=False),
    NestedField(10, "updated_by", StringType(), required=False),
    NestedField(11, "isEditable", BooleanType(), required=True),
    NestedField(12, "isApiIntegrated", BooleanType(), required=True),
    NestedField(13, "branch_list", StringType(), required=False),
    NestedField(14, "branch_code_list", StringType(), required=False),
]

# Drivers_schema
Drivers_schema = [
    NestedField(1, "id", StringType(), required=True),
    NestedField(2, "time_sorted_id", StringType()),
    NestedField(3, "type_of_work", StringType()),
    NestedField(4, "employee_from", StringType()),
    NestedField(5, "work_type", StringType()),
    NestedField(6, "firstname", StringType()),
    NestedField(7, "lastname", StringType()),
    NestedField(8, "dob", TimestampType()),
    NestedField(9, "primary_contact", StringType()),
    NestedField(10, "secondary_contact", StringType(), required=False),
    NestedField(11, "address_line1", StringType()),
    NestedField(12, "address_line2", StringType(), required=False),
    NestedField(13, "city", StringType()),
    NestedField(14, "state", StringType()),
    NestedField(15, "pincode", IntegerType()),
    NestedField(16, "area", StringType(), required=False),
    NestedField(17, "country", StringType()),
    NestedField(18, "gender", StringType()),
    NestedField(19, "profile_pic_url", StringType(), required=False),
    NestedField(20, "isActive", IntegerType(), required=False),
    NestedField(21, "remarks", StringType(), required=False),
    NestedField(22, "ratings", StringType(), required=False),
    NestedField(23, "approval_status", StringType(), required=False),
    NestedField(24, "driving_license_num", StringType()),
    NestedField(25, "driving_license_url", StringType()),
    NestedField(26, "driving_license_expiry", TimestampType(), required=False),
    NestedField(27, "aadhar_card_num", StringType()),
    NestedField(28, "aadhar_card_url", StringType()),
    NestedField(29, "voter_id_num", StringType(), required=False),
    NestedField(30, "voter_id_url", StringType(), required=False),
    NestedField(31, "ration_card_num", StringType(), required=False),
    NestedField(32, "ration_card_url", StringType(), required=False),
    NestedField(33, "pancard_num", StringType(), required=False),
    NestedField(34, "pancard_url", StringType(), required=False),
    NestedField(35, "created_on", TimestampType()),
    NestedField(36, "updated_on", TimestampType(), required=False),
    NestedField(37, "created_at", TimestampType()),
    NestedField(38, "updated_at", TimestampType(), required=False),
    NestedField(39, "createdAt", TimestampType()),
    NestedField(40, "updatedAt", TimestampType(), required=False),
    NestedField(41, "created_by", StringType(), required=False),
    NestedField(42, "updated_by", StringType(), required=False),
    NestedField(43, "branch_code_list", StringType(), required=False),
    NestedField(44, "branchcode", StringType(), required=False),
    NestedField(45, "emp_id", StringType(), required=False),
    NestedField(46, "roles", StringType(), required=False),
]

# Exchange_informations
Exchange_informations = [
    NestedField(1, "order_id", StringType(), required=True),
    NestedField(2, "quote_id", StringType(), required=False),
    NestedField(3, "mobile_no", StringType(), required=False),
    NestedField(4, "name", StringType(), required=False),
    NestedField(5, "imei", StringType(), required=False),
    NestedField(6, "item_code", StringType(), required=False),
    NestedField(7, "status", StringType(), required=False),
    NestedField(8, "customer_id", StringType(), required=False),
    NestedField(9, "customer_info", StringType(), required=False),
    NestedField(10, "category", StringType(), required=False),
    NestedField(11, "brand", StringType(), required=False),
    NestedField(12, "product_info", StringType(), required=False),
    NestedField(13, "exchange_quote_details", StringType(), required=False),
    NestedField(14, "branch_code", StringType(), required=False),
    NestedField(15, "confirm_extra_value", StringType(), required=False),
    NestedField(16, "actual_product_value", StringType(), required=False),
    NestedField(17, "actual_exchange_value", StringType(), required=False),
    NestedField(18, "extra_value_comments", StringType(), required=False),
    NestedField(19, "extra_value", StringType(), required=False),
    NestedField(20, "device_evaluation", StringType(), required=False),
    NestedField(21, "device_images", StringType(), required=False),
    NestedField(22, "created_at", TimestampType(), required=False),
    NestedField(23, "designation", StringType(), required=False),
    NestedField(24, "created_by", StringType(), required=False),
    NestedField(25, "vendor_id", StringType(), required=False),
    NestedField(26, "vendor_name", StringType(), required=False),
    NestedField(27, "device_condition", StringType(), required=False),
]

# Exchange_masterorders_w
Exchange_masterorders_w = [
    NestedField(1, "order_id", StringType(), required=True),
    NestedField(2, "sale_order_id", StringType(), required=True),
    NestedField(3, "invoice_no", StringType(), required=False),
    NestedField(4, "invoice_date", TimestampType(), required=False),
    NestedField(5, "invoice_reff_no", StringType(), required=False),
    NestedField(6, "invoice_reff_date", StringType(), required=False),
    NestedField(7, "channel", StringType(), required=False),
    NestedField(8, "channel_medium", StringType(), required=False),
    NestedField(9, "order_status", StringType(), required=False),
    NestedField(10, "order_tag", StringType(), required=False),
    NestedField(11, "order_inv_status", StringType(), required=False),
    NestedField(12, "order_type", StringType(), required=False),
    NestedField(13, "delivery_from", StringType(), required=False),
    NestedField(14, "delivery_from_branchcode", StringType(), required=False),
    NestedField(15, "billing_branch_code", StringType(), required=False),
    NestedField(16, "cust_id", StringType(), required=False),
    NestedField(17, "cust_primary_email", StringType(), required=False),
    NestedField(18, "cust_primary_contact", StringType(), required=False),
    NestedField(19, "cust_mobile", StringType(), required=False),
    NestedField(20, "customer_address", StringType(), required=False),
    NestedField(21, "shipment_address", StringType(), required=False),
    NestedField(22, "latitude", DoubleType(), required=False),
    NestedField(23, "longitude", DoubleType(), required=False),
    NestedField(24, "billing_address", StringType(), required=False),
    NestedField(25, "payment_details", StringType(), required=False),
    NestedField(26, "refund_details", StringType(), required=False),
    NestedField(27, "voucher_details", StringType(), required=False),
    NestedField(28, "employee_sale_details", StringType(), required=False),
    NestedField(29, "order_summary_details", StringType(), required=False),
    NestedField(30, "other_details", StringType(), required=False),
    NestedField(31, "invoice_pdf", StringType(), required=False),
    NestedField(32, "lineitems", StringType(), required=False),
    NestedField(33, "lineitem_status", StringType(), required=False),
    NestedField(34, "created_at", TimestampType(), required=False),
    NestedField(35, "updated_at", TimestampType(), required=False),
    NestedField(36, "created_by", StringType(), required=False),
    NestedField(37, "updated_by", StringType(), required=False),
    NestedField(38, "service_details", StringType(), required=False),
]

# Exchange_masterorders
Exchange_masterorders = [
    NestedField(1, "order_id", StringType(), required=True),
    NestedField(2, "sale_order_id", StringType(), required=True),
    NestedField(3, "invoice_no", StringType(), required=False),
    NestedField(4, "invoice_date", TimestampType(), required=False),
    NestedField(5, "invoice_reff_no", StringType(), required=False),
    NestedField(6, "invoice_reff_date", StringType(), required=False),
    NestedField(7, "channel", StringType(), required=False),
    NestedField(8, "channel_medium", StringType(), required=False),
    NestedField(9, "order_status", StringType(), required=False),
    NestedField(10, "order_tag", StringType(), required=False),
    NestedField(11, "order_inv_status", StringType(), required=False),
    NestedField(12, "order_type", StringType(), required=False),
    NestedField(13, "delivery_from", StringType(), required=False),
    NestedField(14, "delivery_from_branchcode", StringType(), required=False),
    NestedField(15, "billing_branch_code", StringType(), required=False),
    NestedField(16, "cust_id", StringType(), required=False),
    NestedField(17, "cust_primary_email", StringType(), required=False),
    NestedField(18, "cust_primary_contact", StringType(), required=False),
    NestedField(19, "cust_mobile", StringType(), required=False),
    NestedField(20, "customer_address", StringType(), required=False),
    NestedField(21, "shipment_address", StringType(), required=False),
    NestedField(22, "latitude", DoubleType(), required=False),
    NestedField(23, "longitude", DoubleType(), required=False),
    NestedField(24, "billing_address", StringType(), required=False),
    NestedField(25, "payment_details", StringType(), required=False),
    NestedField(26, "refund_details", StringType(), required=False),
    NestedField(27, "voucher_details", StringType(), required=False),
    NestedField(28, "employee_sale_details", StringType(), required=False),
    NestedField(29, "order_summary_details", StringType(), required=False),
    NestedField(30, "other_details", StringType(), required=False),
    NestedField(31, "service_details", StringType(), required=False),
    NestedField(32, "invoice_pdf", StringType(), required=False),
    NestedField(33, "lineitems", StringType(), required=False),
    NestedField(34, "lineitem_status", StringType(), required=False),
    NestedField(35, "created_at", TimestampType(), required=False),
    NestedField(36, "created_by", StringType(), required=False),
    NestedField(37, "updated_by", StringType(), required=False),
    NestedField(38, "updated_at", TimestampType(), required=False),
]

# Exchange_orderlineitems
Exchange_orderlineitems = [
    NestedField(1, "line_item_id", StringType(), required=True),
    NestedField(2, "order_line_item_id", StringType(), required=True),
    NestedField(3, "master_order_id", StringType(), required=True),
    NestedField(4, "master_sale_order_id", StringType(), required=True),
    NestedField(5, "delivery_from", StringType(), required=False),
    NestedField(6, "customer_status", StringType(), required=False),
    NestedField(7, "inventory_status", StringType(), required=False),
    NestedField(8, "internal_status", StringType(), required=False),
    NestedField(9, "shipping_status", StringType(), required=False),
    NestedField(10, "category_code", StringType(), required=False),
    NestedField(11, "category_name", StringType(), required=False),
    NestedField(12, "item_qty_label", StringType(), required=False),
    NestedField(13, "exg_invo_no", StringType(), required=False),
    NestedField(14, "exg_invo_date", StringType(), required=False),
    NestedField(15, "home_pickup", StringType(), required=False),
    NestedField(16, "order_inv_status", StringType(), required=False),
    NestedField(17, "slug", StringType(), required=False),
    NestedField(18, "product_name", StringType(), required=False),
    NestedField(19, "model", StringType(), required=False),
    NestedField(20, "erp_item_code", StringType(), required=False),
    NestedField(21, "quantity", IntegerType(), required=False),
    NestedField(22, "type_of_order", StringType(), required=False),
    NestedField(23, "product_hsn", StringType(), required=False),
    NestedField(24, "image", StringType(), required=False),
    NestedField(25, "options", StringType(), required=False),
    NestedField(26, "delivery_charges", StringType(), required=False),
    NestedField(27, "price", StringType(), required=False),
    NestedField(28, "special_price", IntegerType(), required=False),
    NestedField(29, "brand_code", StringType(), required=False),
    NestedField(30, "brand_name", StringType(), required=False),
    NestedField(31, "product_policy", StringType(), required=False),
    NestedField(32, "billed_details", StringType(), required=False),
    NestedField(33, "delivery_details", StringType(), required=False),
    NestedField(34, "invoice_details", StringType(), required=False),
    NestedField(35, "tax_details", StringType(), required=False),
    NestedField(36, "insurance_details", StringType(), required=False),
    NestedField(37, "preorder_response", StringType(), required=False),
    NestedField(38, "seller_details", StringType(), required=False),
    NestedField(39, "shipment_details", StringType(), required=False),
    NestedField(40, "return_details", StringType(), required=False),
    NestedField(41, "return_refund_details", StringType(), required=False),
    NestedField(42, "return_replace_details", StringType(), required=False),
    NestedField(43, "return_exchange_details", StringType(), required=False),
    NestedField(44, "created_at", TimestampType(), required=False),
    NestedField(45, "updated_at", TimestampType(), required=False),
    NestedField(46, "created_by", StringType(), required=False),
    NestedField(47, "updated_by", StringType(), required=False),
    NestedField(48, "serial_no", StringType(), required=False),
]

# ExternalCallLogs
ExternalCallLogs = [
    NestedField(1, "id", StringType(), required=True),
    NestedField(2, "ext_log_id", StringType(), required=False),
    NestedField(3, "short_code", StringType(), required=False),
    NestedField(4, "invoice_no", StringType(), required=False),
    NestedField(5, "res_obj", StringType(), required=False),
    NestedField(6, "created_at", TimestampType(), required=False),
    NestedField(7, "created_by", StringType(), required=False),
]

# Hub_masters
Hub_masters = [
    NestedField(1, "id", StringType(), required=True),
    NestedField(2, "store_name", StringType(), required=True),
    NestedField(3, "state", StringType(), required=True),
    NestedField(4, "district", StringType(), required=True),
    NestedField(5, "store_mobile_no", StringType(), required=True),
    NestedField(6, "store_mailid", StringType(), required=True),
    NestedField(7, "store_shortcode", StringType(), required=True),
    NestedField(8, "pincode", StringType(), required=True),
    NestedField(9, "customer_code", StringType(), required=True),
    NestedField(10, "store_address", StringType(), required=True),
    NestedField(11, "store_address_line1", StringType(), required=True),
    NestedField(12, "store_address_line2", StringType(), required=False),
    NestedField(13, "store_address_line3", StringType(), required=True),
    NestedField(14, "area_code", StringType(), required=True),
    NestedField(15, "login_user", StringType(), required=True),
    NestedField(16, "created_at", TimestampType(), required=False),
    NestedField(17, "updated_at", TimestampType(), required=False),
    NestedField(18, "created_by", StringType(), required=False),
    NestedField(19, "updated_by", StringType(), required=False),
    NestedField(20, "isactive", IntegerType(), required=True),
    NestedField(21, "store_contact_person", StringType(), required=True),
]

# Installation_services
Installation_services = [
    NestedField(1, "id", StringType(), required=True),
    NestedField(2, "service_type", StringType(), required=True),
    NestedField(3, "order_id", StringType(), required=False),
    NestedField(4, "item_code", StringType(), required=False),
    NestedField(5, "item_image", StringType(), required=False),
    NestedField(6, "item_name", StringType(), required=False),
    NestedField(7, "item_serial_no", StringType(), required=False),
    NestedField(8, "invoice_no", StringType(), required=False),
    NestedField(9, "installation_status", StringType(), required=True),
    NestedField(10, "installation_sub_status", StringType(), required=False),
    NestedField(11, "installation_rating", StringType(), required=False),
    NestedField(12, "installation_remarks", StringType(), required=False),
    NestedField(13, "installation_address", StringType(), required=False),
    NestedField(14, "installation_call_booking_date", StringType(), required=False),
    NestedField(15, "installation_completed_date", StringType(), required=False),
    NestedField(16, "installation_call_booking_number", StringType(), required=False),
    NestedField(17, "created_at", TimestampType(), required=True),
    NestedField(18, "created_by", StringType(), required=False),
]

# Intransit_manifests
Intransit_manifests = [
    NestedField(1, "t_manifest_id", StringType(), required=True),
    NestedField(2, "t_shipment_id", StringType(), required=True),
    NestedField(3, "time_sorted_id", StringType(), required=True),
    NestedField(4, "manifest_type", StringType(), required=False),
    NestedField(5, "items_total", IntegerType(), required=True),
    NestedField(6, "created_by", StringType(), required=False),
    NestedField(7, "updated_by", StringType(), required=False),
    NestedField(8, "createdAt", TimestampType(), required=True),
    NestedField(9, "updatedAt", TimestampType(), required=False),
    NestedField(10, "created_at", TimestampType(), required=True),
    NestedField(11, "updated_at", TimestampType(), required=False),
]


intransit_pickup_delivery_items = [
    NestedField(1, "intransit_pickupdelivery_id", StringType(), required=True),
    NestedField(2, "pickup_delivery_req_item_id", StringType(), required=True),
    NestedField(3, "pickup_delivery_req_id", StringType(), required=True),
    NestedField(4, "order_id", StringType(), required=True),
    NestedField(5, "sale_order_id", StringType(), required=True),
    NestedField(6, "invoice_no", StringType(), required=False),
    NestedField(7, "invoice_date", TimestampType(), required=False),
    NestedField(8, "invoice_reff_no", StringType(), required=False),
    NestedField(9, "invoice_reff_date", StringType(), required=False),
    NestedField(10, "expect_delivery_pickup_dt", TimestampType(), required=True),
    NestedField(11, "customer_status", StringType(), required=False),
    NestedField(12, "internal_status", StringType(), required=True),
    NestedField(13, "inventory_status", StringType(), required=False),
    NestedField(14, "shipment_status", StringType(), required=False),
    NestedField(15, "inventory_location_code", StringType(), required=True),
    NestedField(16, "docking_area", StringType(), required=False),
    NestedField(17, "docking_area_code", StringType(), required=False),
    NestedField(18, "type_of_order", StringType(), required=False),
    NestedField(19, "item_code", StringType(), required=True),
    NestedField(20, "item_name", StringType(), required=True),
    NestedField(21, "item_image", StringType(), required=True),
    NestedField(22, "item_weight", StringType(), required=False),
    NestedField(23, "item_qty", IntegerType(), required=True),
    NestedField(24, "category_code", StringType(), required=False),
    NestedField(25, "category_name", StringType(), required=False),
    NestedField(26, "inventory_location", StringType(), required=True),
    NestedField(27, "inventory_location_branchname", StringType(), required=False),
    NestedField(28, "inventory_location_mobileno", StringType(), required=False),
    NestedField(29, "order_type", StringType(), required=False),
    NestedField(30, "order_line_item_id", StringType(), required=False),
    NestedField(31, "picklist_id", StringType(), required=False),
    NestedField(32, "picker_id", StringType(), required=False),
    NestedField(33, "picker_details", StringType(), required=False),
    NestedField(34, "picker_added_dt", TimestampType(), required=False),
    NestedField(35, "t_manifest_id", StringType(), required=True),
    NestedField(36, "manifest_added_dt", TimestampType(), required=False),
    NestedField(37, "t_shipment_id", StringType(), required=True),
    NestedField(38, "driver_code", StringType(), required=False),
    NestedField(39, "driver_name", StringType(), required=False),
    NestedField(40, "driver_image", StringType(), required=False),
    NestedField(41, "driver_contact", StringType(), required=False),
    NestedField(42, "assistant_code", StringType(), required=False),
    NestedField(43, "assistant_name", StringType(), required=False),
    NestedField(44, "assistant_pic", StringType(), required=False),
    NestedField(45, "assistant_contact", StringType(), required=False),
    NestedField(46, "vehicle_no", StringType(), required=False),
    NestedField(47, "vehicle_type", StringType(), required=False),
    NestedField(48, "vehicle_name", StringType(), required=False),
    NestedField(49, "vehicle_image", StringType(), required=False),
    NestedField(50, "order_tag", StringType(), required=False),
    NestedField(51, "order_inv_status", StringType(), required=False),
    NestedField(52, "tracking_id", StringType(), required=False),
    NestedField(53, "tracking_url", StringType(), required=False),
    NestedField(54, "permit", StringType(), required=True),
    NestedField(55, "courier_name", StringType(), required=False),
    NestedField(56, "courier_details", StringType(), required=False),
    NestedField(57, "ispickup_active", BooleanType(), required=True),
    NestedField(58, "dimension_length", IntegerType(), required=False),
    NestedField(59, "dimension_height", IntegerType(), required=False),
    NestedField(60, "dimension_width", IntegerType(), required=False),
    NestedField(61, "dimension_units", StringType(), required=False),
    NestedField(62, "latitude", DoubleType(), required=False),
    NestedField(63, "longitude", DoubleType(), required=False),
    NestedField(64, "inventory_location_address", StringType(), required=False),
    NestedField(65, "status_notification", StringType(), required=False),
    NestedField(66, "item_price", StringType(), required=False),
    NestedField(67, "item_qty_label", StringType(), required=False),
    NestedField(68, "item_dimension", StringType(), required=False),
    NestedField(69, "line_itemid", StringType(), required=False),
    NestedField(70, "invoice_status", StringType(), required=False),
    NestedField(71, "exchange_invo_no", StringType(), required=False),
    NestedField(72, "exchange_invo_date", TimestampType(), required=False),
    NestedField(73, "exchange_invoice_url", StringType(), required=False),
    NestedField(74, "exchange_collected_amount", StringType(), required=False),
    NestedField(75, "brand", StringType(), required=False),
    NestedField(76, "capture_do_url", StringType(), required=False),
    NestedField(77, "shipment_tracking_id", StringType(), required=False),
    NestedField(78, "shipping_label_url", StringType(), required=False),
    NestedField(79, "reattempt_count", IntegerType(), required=False),
    NestedField(80, "secondary_assistant_code", StringType(), required=False),
    NestedField(81, "secondary_assistant_name", StringType(), required=False),
    NestedField(82, "secondary_assistant_pic", StringType(), required=False),
    NestedField(83, "secondary_assistant_contact", StringType(), required=False),
    NestedField(84, "pickup_label_id", StringType(), required=False),
    NestedField(85, "collection_location_type", StringType(), required=False),
    NestedField(86, "collection_location_code", StringType(), required=False),
    NestedField(87, "collection_location_branchname", StringType(), required=False),
    NestedField(88, "collection_location_address", StringType(), required=False),
    NestedField(89, "collection_location_mobileno", StringType(), required=False),
    NestedField(90, "collection_docking_area", StringType(), required=False),
    NestedField(91, "collection_docking_area_code", StringType(), required=False),
    NestedField(92, "to_location_fullname", StringType(), required=False),
    NestedField(93, "to_location_email", StringType(), required=False),
    NestedField(94, "to_location_mobileno", StringType(), required=False),
    NestedField(95, "to_location_address", StringType(), required=False),
    NestedField(96, "to_location_pincode", IntegerType(), required=True),
    NestedField(97, "to_location_lat_long", StringType(), required=False),
    NestedField(98, "shipment_type", StringType(), required=False),
    NestedField(99, "home_pickup", StringType(), required=False),
    NestedField(100, "row_added_dt", TimestampType(), required=True),
    NestedField(101, "row_updated_dt", TimestampType(), required=False),
    NestedField(102, "row_added_by", StringType(), required=True),
    NestedField(103, "row_updated_by", StringType(), required=False),
    NestedField(104, "goods_received_date", TimestampType(), required=False),
    NestedField(105, "courier_code", StringType(), required=False),
    NestedField(106, "billing_branch_code", StringType(), required=False),
    NestedField(107, "otp_verified_status", BooleanType(), required=False),
    NestedField(108, "item_serial_no", StringType(), required=False),
    NestedField(109, "selling_price", StringType(), required=False),
    NestedField(110, "vendor_name", StringType(), required=False),
    NestedField(111, "vendor_id", StringType(), required=False),
    NestedField(112, "vendor_details", StringType(), required=False),
    NestedField(113, "sale_invoice_no", StringType(), required=False),
    NestedField(114, "sale_invoice_date", DateType(), required=False),
    NestedField(115, "quote_id", StringType(), required=False),
    NestedField(116, "tracking_details", StringType(), required=False),
]


intransit_shipments = [
    NestedField(1, "t_shipment_id", StringType(), required=True),
    NestedField(2, "time_sorted_id", StringType(), required=True),
    NestedField(3, "shipment_type", StringType(), required=True),
    NestedField(4, "fulfiled_by", StringType(), required=False),
    NestedField(5, "provider", StringType(), required=True),
    NestedField(6, "branch_code", StringType(), required=False),
    NestedField(7, "collection_branch_code", StringType(), required=True),
    NestedField(8, "status", StringType(), required=True),
    NestedField(9, "vehicle_no", StringType(), required=False),
    NestedField(10, "vehicle_type", StringType(), required=False),
    NestedField(11, "vehicle_image", StringType(), required=False),
    NestedField(12, "vehicle_name", StringType(), required=False),
    NestedField(13, "driver_code", StringType(), required=False),
    NestedField(14, "driver_name", StringType(), required=False),
    NestedField(15, "driver_image", StringType(), required=False),
    NestedField(16, "driver_contact", StringType(), required=False),
    NestedField(17, "assistant_code", StringType(), required=False),
    NestedField(18, "assistant_name", StringType(), required=False),
    NestedField(19, "assistant_pic", StringType(), required=False),
    NestedField(20, "assistant_contact", StringType(), required=False),
    NestedField(21, "secondary_assistant_code", StringType(), required=False),
    NestedField(22, "secondary_assistant_name", StringType(), required=False),
    NestedField(23, "secondary_assistant_pic", StringType(), required=False),
    NestedField(24, "secondary_assistant_contact", StringType(), required=False),
    NestedField(25, "tracking_id", StringType(), required=False),
    NestedField(26, "tracking_url", StringType(), required=False),
    NestedField(27, "courier_name", StringType(), required=False),
    NestedField(28, "dimension_length", IntegerType(), required=False),
    NestedField(29, "dimension_height", IntegerType(), required=False),
    NestedField(30, "dimension_width", IntegerType(), required=False),
    NestedField(31, "dimension_units", StringType(), required=False),
    NestedField(32, "permit", StringType(), required=False),
    NestedField(33, "created_at", TimestampType(), required=True),
    NestedField(34, "updated_at", TimestampType(), required=False),
    NestedField(35, "createdAt", TimestampType(), required=True),
    NestedField(36, "updatedAt", TimestampType(), required=False),
    NestedField(37, "created_by", StringType(), required=False),
    NestedField(38, "updated_by", StringType(), required=False),
    NestedField(39, "courier_code", StringType(), required=False),

]

invoice_masters = [
    NestedField(1, "id", StringType(), required=True),
    NestedField(2, "invoice_code", StringType(), required=True),
    NestedField(3, "invoice_branch", StringType(), required=False),
    NestedField(4, "invoice_no", IntegerType(), required=True),
    NestedField(5, "invoice_year", StringType(), required=True),
    NestedField(6, "order_type", StringType(), required=False),
    NestedField(7, "created_at", TimestampType(), required=True),
    NestedField(8, "updated_at", TimestampType(), required=True),
]

manifests = [
    NestedField(1, "time_sorted_id", StringType(), required=True),
    NestedField(2, "manifest_id", StringType(), required=True),
    NestedField(3, "manifest_type", StringType(), required=False),
    NestedField(4, "shipment_id", StringType(), required=True),
    NestedField(5, "items_total", IntegerType(), required=True),
    NestedField(6, "created_by", StringType(), required=False),
    NestedField(7, "updated_by", StringType(), required=False),
    NestedField(8, "createdAt", TimestampType(), required=True),
    NestedField(9, "updatedAt", TimestampType(), required=False),
    NestedField(10, "created_at", TimestampType(), required=True),
    NestedField(11, "updated_at", TimestampType(), required=False),
]

pick_lists = [
    NestedField(1, "picklist_id", StringType(), required=True),
    NestedField(2, "id", StringType(), required=True),
    NestedField(3, "allocate_picker_by", StringType(), required=False),
    NestedField(4, "branch_code", StringType(), required=False),
    NestedField(5, "items", StringType(), required=True),
    NestedField(6, "pickers", StringType(), required=True),
    NestedField(7, "items_total", IntegerType(), required=False),
    NestedField(8, "pickers_total", IntegerType(), required=False),
    NestedField(9, "ispickup_active", BooleanType(), required=True),
    NestedField(10, "picklist_status", StringType(), required=True),
    NestedField(11, "created_on", TimestampType(), required=True),
    NestedField(12, "updated_on", TimestampType(), required=False),
    NestedField(13, "created_by", StringType(), required=False),
    NestedField(14, "updated_by", StringType(), required=False),
    NestedField(15, "created_at", TimestampType(), required=True),
    NestedField(16, "updated_at", TimestampType(), required=False),

]

pickup_deliveries = [
    NestedField(1, "pickup_delivery_req_id", StringType(), required=True),
    NestedField(2, "order_id", StringType(), required=False),
    NestedField(3, "sale_order_id", StringType(), required=False),
    NestedField(4, "invoice_no", StringType(), required=False),
    NestedField(5, "invoice_date", TimestampType(), required=False),
    NestedField(6, "invoice_reff_no", StringType(), required=False),
    NestedField(7, "invoice_reff_date", StringType(), required=False),
    NestedField(8, "request_type", StringType(), required=False),
    NestedField(9, "inventory_details", StringType(), required=False),
    NestedField(10, "return_details", StringType(), required=False),
    NestedField(11, "collection_details", StringType(), required=False),
    NestedField(12, "to_details", StringType(), required=False),
    NestedField(13, "shipment_details", StringType(), required=False),
    NestedField(14, "order_details", StringType(), required=False),
    NestedField(15, "expected", TimestampType(), required=False),
    NestedField(16, "is_accepted", IntegerType(), required=False),
    NestedField(17, "rejection_reason", StringType(), required=False),
    NestedField(18, "latitude", DoubleType(), required=False),
    NestedField(19, "longitude", DoubleType(), required=False),
    NestedField(20, "invoice_status", StringType(), required=False),
    NestedField(21, "order_type", StringType(), required=False),
    NestedField(22, "order_inv_status", StringType(), required=False),
    NestedField(23, "row_added_dttm", TimestampType(), required=False),
    NestedField(24, "row_added_by", StringType(), required=False),
    NestedField(25, "row_updated_by", StringType(), required=False),
    NestedField(26, "row_updated_dttm", TimestampType(), required=False),
    NestedField(27, "oms_data_migration_status", IntegerType(), required=False),
    NestedField(28, "updated_at_new", TimestampType(), required=False),

]

reason_messages = [
    NestedField(1, "id", IntegerType(), required=True),
    NestedField(2, "time_sorted_id", StringType(), required=False),
    NestedField(3, "status", StringType(), required=False),
    NestedField(4, "channel", StringType(), required=False),
    NestedField(5, "type", StringType(), required=False),
    NestedField(6, "msg", StringType(), required=False),
    NestedField(7, "created_at", TimestampType(), required=True),

]

return_masterorders = [
    NestedField(1, "order_id", StringType(), required=True),
    NestedField(2, "sale_order_id", StringType(), required=True),
    NestedField(3, "invoice_no", StringType(), required=False),
    NestedField(4, "invoice_date", TimestampType(), required=False),
    NestedField(5, "invoice_reff_no", StringType(), required=False),
    NestedField(6, "invoice_reff_date", StringType(), required=False),
    NestedField(7, "channel", StringType(), required=False),
    NestedField(8, "channel_medium", StringType(), required=False),
    NestedField(9, "order_status", StringType(), required=False),
    NestedField(10, "order_tag", StringType(), required=False),
    NestedField(11, "order_inv_status", StringType(), required=False),
    NestedField(12, "order_type", StringType(), required=False),
    NestedField(13, "delivery_from", StringType(), required=False),
    NestedField(14, "delivery_from_branchcode", StringType(), required=False),
    NestedField(15, "billing_branch_code", StringType(), required=False),
    NestedField(16, "cust_id", StringType(), required=False),
    NestedField(17, "cust_primary_email", StringType(), required=False),
    NestedField(18, "cust_primary_contact", StringType(), required=False),
    NestedField(19, "cust_mobile", StringType(), required=False),
    NestedField(20, "customer_address", StringType(), required=False),
    NestedField(21, "shipment_address", StringType(), required=False),
    NestedField(22, "latitude", DoubleType(), required=False),
    NestedField(23, "longitude", DoubleType(), required=False),
    NestedField(24, "billing_address", StringType(), required=False),
    NestedField(25, "lineitems", BinaryType(), required=False),
    NestedField(26, "lineitem_status", StringType(), required=False),
    NestedField(27, "payment_details", StringType(), required=False),
    NestedField(28, "refund_details", StringType(), required=False),
    NestedField(29, "voucher_details", StringType(), required=False),
    NestedField(30, "employee_sale_details", StringType(), required=False),
    NestedField(31, "order_summary_details", StringType(), required=False),
    NestedField(32, "other_details", StringType(), required=False),
    NestedField(33, "service_details", StringType(), required=False),
    NestedField(34, "invoice_pdf", StringType(), required=False),
    NestedField(35, "created_at", TimestampType(), required=False),
    NestedField(36, "updated_at", TimestampType(), required=False),
    NestedField(37, "created_by", StringType(), required=False),
    NestedField(38, "updated_by", StringType(), required=False),
    NestedField(39, "multi_invoice", StringType(), required=False),

]

return_masterorders_w = [
    NestedField(1, "order_id", StringType(), required=True),
    NestedField(2, "sale_order_id", StringType(), required=True),
    NestedField(3, "invoice_no", StringType(), required=False),
    NestedField(4, "invoice_date", TimestampType(), required=False),
    NestedField(5, "invoice_reff_no", StringType(), required=False),
    NestedField(6, "invoice_reff_date", StringType(), required=False),
    NestedField(7, "channel", StringType(), required=False),
    NestedField(8, "channel_medium", StringType(), required=False),
    NestedField(9, "order_status", StringType(), required=False),
    NestedField(10, "order_tag", StringType(), required=False),
    NestedField(11, "order_inv_status", StringType(), required=False),
    NestedField(12, "order_type", StringType(), required=False),
    NestedField(13, "delivery_from", StringType(), required=False),
    NestedField(14, "delivery_from_branchcode", StringType(), required=False),
    NestedField(15, "billing_branch_code", StringType(), required=False),
    NestedField(16, "cust_id", StringType(), required=False),
    NestedField(17, "cust_primary_email", StringType(), required=False),
    NestedField(18, "cust_primary_contact", StringType(), required=False),
    NestedField(19, "cust_mobile", StringType(), required=False),
    NestedField(20, "customer_address", StringType(), required=False),
    NestedField(21, "shipment_address", StringType(), required=False),
    NestedField(22, "latitude", DoubleType(), required=False),
    NestedField(23, "longitude", DoubleType(), required=False),
    NestedField(24, "billing_address", StringType(), required=False),
    NestedField(25, "lineitems", StringType(), required=False),
    NestedField(26, "lineitem_status", StringType(), required=False),
    NestedField(27, "payment_details", StringType(), required=False),
    NestedField(28, "refund_details", StringType(), required=False),
    NestedField(29, "voucher_details", StringType(), required=False),
    NestedField(30, "employee_sale_details", StringType(), required=False),
    NestedField(31, "order_summary_details", StringType(), required=False),
    NestedField(32, "other_details", StringType(), required=False),
    NestedField(33, "service_details", StringType(), required=False),
    NestedField(34, "invoice_pdf", StringType(), required=False),
    NestedField(35, "created_at", TimestampType(), required=False),
    NestedField(36, "updated_at", TimestampType(), required=False),
    NestedField(37, "created_by", StringType(), required=False),
    NestedField(38, "updated_by", StringType(), required=False),
    NestedField(39, "multi_invoice", StringType(), required=False),

]

return_orderlineitems = [
    NestedField(1, "line_item_id", StringType(), required=True),
    NestedField(2, "order_line_item_id", StringType(), required=True),
    NestedField(3, "master_order_id", StringType(), required=True),
    NestedField(4, "master_sale_order_id", StringType(), required=True),
    NestedField(5, "delivery_from", StringType(), required=False),
    NestedField(6, "customer_status", StringType(), required=False),
    NestedField(7, "inventory_status", StringType(), required=False),
    NestedField(8, "internal_status", StringType(), required=False),
    NestedField(9, "shipping_status", StringType(), required=False),
    NestedField(10, "category_code", StringType(), required=False),
    NestedField(11, "category_name", StringType(), required=False),
    NestedField(12, "item_qty_label", StringType(), required=False),
    NestedField(13, "exg_invo_no", StringType(), required=False),
    NestedField(14, "exg_invo_date", StringType(), required=False),
    NestedField(15, "home_pickup", StringType(), required=False),
    NestedField(16, "order_inv_status", StringType(), required=False),
    NestedField(17, "slug", StringType(), required=False),
    NestedField(18, "product_name", StringType(), required=False),
    NestedField(19, "model", StringType(), required=False),
    NestedField(20, "erp_item_code", StringType(), required=False),
    NestedField(21, "quantity", IntegerType(), required=False),
    NestedField(22, "type_of_order", StringType(), required=False),
    NestedField(23, "product_hsn", StringType(), required=False),
    NestedField(24, "image", StringType(), required=False),
    NestedField(25, "options", StringType(), required=False),
    NestedField(26, "delivery_charges", StringType(), required=False),
    NestedField(27, "price", StringType(), required=False),
    NestedField(28, "special_price", IntegerType(), required=False),
    NestedField(29, "brand_code", StringType(), required=False),
    NestedField(30, "brand_name", StringType(), required=False),
    NestedField(31, "product_policy", StringType(), required=False),
    NestedField(32, "billed_details", StringType(), required=False),
    NestedField(33, "delivery_details", StringType(), required=False),
    NestedField(34, "invoice_details", StringType(), required=False),
    NestedField(35, "tax_details", StringType(), required=False),
    NestedField(36, "insurance_details", StringType(), required=False),
    NestedField(37, "preorder_response", StringType(), required=False),
    NestedField(38, "seller_details", StringType(), required=False),
    NestedField(39, "shipment_details", StringType(), required=False),
    NestedField(40, "return_details", StringType(), required=False),
    NestedField(41, "return_refund_details", StringType(), required=False),
    NestedField(42, "return_replace_details", StringType(), required=False),
    NestedField(43, "return_exchange_details", StringType(), required=False),
    NestedField(44, "created_at", TimestampType(), required=False),
    NestedField(45, "updated_at", TimestampType(), required=False),
    NestedField(46, "created_by", StringType(), required=False),
    NestedField(47, "updated_by", StringType(), required=False),
    NestedField(48, "serial_no", StringType(), required=False),

]

roles = [
    NestedField(1, "time_sorted_id", StringType(), required=True),
    NestedField(2, "code", StringType(), required=True),
    NestedField(3, "name", StringType(), required=False),
    NestedField(4, "permissions", StringType(), required=True),
    NestedField(5, "isEditable", BooleanType(), required=False),
    NestedField(6, "isActive", BooleanType(), required=False),
    NestedField(7, "created_on", TimestampType(), required=True),
    NestedField(8, "updated_on", TimestampType(), required=False),
    NestedField(9, "created_at", TimestampType(), required=True),
    NestedField(10, "updated_at", TimestampType(), required=False),
    NestedField(11, "created_by", StringType(), required=False),
    NestedField(12, "updated_by", StringType(), required=False),
    NestedField(13, "createdAt", TimestampType(), required=True),
    NestedField(14, "updatedAt", TimestampType(), required=True),
    NestedField(15, "is_multi_branch_role", BooleanType(), required=False),
    NestedField(16, "role_type", StringType(), required=False),

]

scheduler_retention_log = [
    NestedField(1, "id", StringType(), required=True),
    NestedField(2, "operation_type", StringType(), required=False),
    NestedField(3, "affected_rows", IntegerType(), required=False),
    NestedField(4, "status", StringType(), required=False),
    NestedField(5, "message", StringType(), required=False),
    NestedField(6, "created_at", TimestampType(), required=False),

]

schedulers = [
    NestedField(1, "job_id", StringType(), required=True),
    NestedField(2, "job_status", StringType(), required=False),
    NestedField(3, "job_type", StringType(), required=False),
    NestedField(4, "job_start_on", TimestampType(), required=True),
    NestedField(5, "query_obj", StringType(), required=False),
    NestedField(6, "input_gcp_url", StringType(), required=False),
    NestedField(7, "output_gcp_url", StringType(), required=False),
    NestedField(8, "error_gcp_url", StringType(), required=False),
    NestedField(9, "error_msg", StringType(), required=False),
    NestedField(10, "time_taken", StringType(), required=False),
    NestedField(11, "branch_code", StringType(), required=False),
    NestedField(12, "invoice_no", StringType(), required=False),
    NestedField(13, "created_on", TimestampType(), required=True),
    NestedField(14, "updated_on", TimestampType(), required=False),
    NestedField(15, "created_at", TimestampType(), required=True),
    NestedField(16, "updated_at", TimestampType(), required=False),
    NestedField(17, "created_by", StringType(), required=False),
    NestedField(18, "updated_by", StringType(), required=False),

]

schedulers_w = [
    NestedField(1, "job_id", StringType(), required=True),
    NestedField(2, "job_status", StringType(), required=False),
    NestedField(3, "job_type", StringType(), required=False),
    NestedField(4, "job_start_on", TimestampType(), required=True),
    NestedField(5, "query_obj", StringType(), required=False),
    NestedField(6, "input_gcp_url", StringType(), required=False),
    NestedField(7, "output_gcp_url", StringType(), required=False),
    NestedField(8, "error_gcp_url", StringType(), required=False),
    NestedField(9, "error_msg", StringType(), required=False),
    NestedField(10, "time_taken", StringType(), required=False),
    NestedField(11, "branch_code", StringType(), required=False),
    NestedField(12, "invoice_no", StringType(), required=False),
    NestedField(13, "created_on", TimestampType(), required=True),
    NestedField(14, "updated_on", TimestampType(), required=False),
    NestedField(15, "created_at", TimestampType(), required=True),
    NestedField(16, "updated_at", TimestampType(), required=False),
    NestedField(17, "created_by", StringType(), required=False),
    NestedField(18, "updated_by", StringType(), required=False),

]

service_history_c = [
    NestedField(1, "id", StringType(), required=True),
    NestedField(2, "service_id", StringType(), required=True),
    NestedField(3, "order_id", StringType(), required=True),
    NestedField(4, "invoice_no", StringType(), required=True),
    NestedField(5, "item_code", StringType(), required=True),
    NestedField(6, "item_serial_no", StringType(), required=True),
    NestedField(7, "status", StringType(), required=True),
    NestedField(8, "remarks", StringType(), required=False),
    NestedField(9, "additional_info", StringType(), required=False),
    NestedField(10, "created_at", TimestampType(), required=True),
    NestedField(11, "updated_at", TimestampType(), required=True),
    NestedField(12, "created_by", StringType(), required=False),
    NestedField(13, "updated_by", StringType(), required=False),
    NestedField(14, "service_type", StringType(), required=False),
]

service_history_h = [
    NestedField(1, "id", StringType(), required=True),
    NestedField(2, "service_id", StringType(), required=False),
    NestedField(3, "order_id", StringType(), required=False),
    NestedField(4, "invoice_no", StringType(), required=False),
    NestedField(5, "item_code", StringType(), required=False),
    NestedField(6, "item_serial_no", StringType(), required=False),
    NestedField(7, "status", StringType(), required=True),
    NestedField(8, "remarks", StringType(), required=False),
    NestedField(9, "additional_info", StringType(), required=False),
    NestedField(10, "created_at", TimestampType(), required=True),
    NestedField(11, "updated_at", TimestampType(), required=True),
    NestedField(12, "created_by", StringType(), required=False),
    NestedField(13, "updated_by", StringType(), required=False),
    NestedField(14, "service_type", StringType(), required=False),

]

service_master_c = [
    NestedField(1, "service_id", StringType(), required=True),
    NestedField(2, "service_type", StringType(), required=True),
    NestedField(3, "order_id", StringType(), required=True),
    NestedField(4, "invoice_no", StringType(), required=True),
    NestedField(5, "item_code", StringType(), required=True),
    NestedField(6, "item_image", StringType(), required=True),
    NestedField(7, "item_name", StringType(), required=True),
    NestedField(8, "item_serial_no", StringType(), required=True),
    NestedField(9, "status", StringType(), required=True),
    NestedField(10, "sub_status", StringType(), required=False),
    NestedField(11, "amount", StringType(), required=False),
    NestedField(12, "service_agent_id", StringType(), required=False),
    NestedField(13, "service_agent_name", StringType(), required=False),
    NestedField(14, "service_agent_mobile_no", StringType(), required=False),
    NestedField(15, "additional_service_agent", StringType(), required=False),
    NestedField(16, "rating", StringType(), required=False),
    NestedField(17, "remarks", StringType(), required=False),
    NestedField(18, "payment_status", StringType(), required=False),
    NestedField(19, "payment_details", StringType(), required=False),
    NestedField(20, "customer_id", StringType(), required=True),
    NestedField(21, "customer_name", StringType(), required=True),
    NestedField(22, "customer_address", StringType(), required=True),
    NestedField(23, "mobile_no", StringType(), required=False),
    NestedField(24, "call_booking_date", DateType(), required=False),
    NestedField(25, "completed_date", StringType(), required=False),
    NestedField(26, "call_booking_number", StringType(), required=False),
    NestedField(27, "created_at", TimestampType(), required=True),
    NestedField(28, "updated_at", TimestampType(), required=True),
    NestedField(29, "created_by", StringType(), required=False),
    NestedField(30, "updated_by", StringType(), required=False),
    NestedField(31, "additional_info", StringType(), required=False),
    NestedField(32, "branch_code", StringType(), required=False),
    NestedField(33, "branch_name", StringType(), required=False),

]

service_master_h = [
    NestedField(1, "service_id", StringType(), required=True),
    NestedField(2, "service_type", StringType(), required=True),
    NestedField(3, "order_id", StringType(), required=True),
    NestedField(4, "invoice_no", StringType(), required=True),
    NestedField(5, "item_code", StringType(), required=True),
    NestedField(6, "item_image", StringType(), required=True),
    NestedField(7, "item_name", StringType(), required=True),
    NestedField(8, "item_serial_no", StringType(), required=True),
    NestedField(9, "status", StringType(), required=True),
    NestedField(10, "sub_status", StringType(), required=False),
    NestedField(11, "amount", StringType(), required=False),
    NestedField(12, "service_agent_id", StringType(), required=False),
    NestedField(13, "service_agent_name", StringType(), required=False),
    NestedField(14, "service_agent_mobile_no", StringType(), required=False),
    NestedField(15, "additional_service_agent", StringType(), required=False),
    NestedField(16, "rating", StringType(), required=False),
    NestedField(17, "remarks", StringType(), required=False),
    NestedField(18, "payment_status", StringType(), required=False),
    NestedField(19, "payment_details", StringType(), required=False),
    NestedField(20, "customer_id", StringType(), required=True),
    NestedField(21, "customer_name", StringType(), required=True),
    NestedField(22, "customer_address", StringType(), required=True),
    NestedField(23, "mobile_no", StringType(), required=False),
    NestedField(24, "call_booking_date", DateType(), required=False),
    NestedField(25, "completed_date", StringType(), required=False),
    NestedField(26, "call_booking_number", StringType(), required=False),
    NestedField(27, "created_at", TimestampType(), required=True),
    NestedField(28, "updated_at", TimestampType(), required=True),
    NestedField(29, "created_by", StringType(), required=False),
    NestedField(30, "updated_by", StringType(), required=False),
    NestedField(31, "additional_info", StringType(), required=False),
    NestedField(32, "branch_code", StringType(), required=False),
    NestedField(33, "branch_name", StringType(), required=False),

]

shipments = [
    NestedField(1, "shipment_id", StringType(), required=True),
    NestedField(2, "time_sorted_id", StringType(), required=True),
    NestedField(3, "fulfiled_by", StringType(), required=False),
    NestedField(4, "provider", StringType(), required=False),
    NestedField(5, "branch_code", StringType(), required=False),
    NestedField(6, "status", StringType(), required=True),
    NestedField(7, "vehicle_no", StringType(), required=False),
    NestedField(8, "vehicle_type", StringType(), required=False),
    NestedField(9, "vehicle_image", StringType(), required=False),
    NestedField(10, "vehicle_name", StringType(), required=False),
    NestedField(11, "driver_code", StringType(), required=False),
    NestedField(12, "driver_name", StringType(), required=False),
    NestedField(13, "driver_image", StringType(), required=False),
    NestedField(14, "driver_contact", StringType(), required=False),
    NestedField(15, "assistant_code", StringType(), required=False),
    NestedField(16, "assistant_name", StringType(), required=False),
    NestedField(17, "assistant_pic", StringType(), required=False),
    NestedField(18, "assistant_contact", StringType(), required=False),
    NestedField(19, "secondary_assistant_code", StringType(), required=False),
    NestedField(20, "secondary_assistant_name", StringType(), required=False),
    NestedField(21, "secondary_assistant_pic", StringType(), required=False),
    NestedField(22, "secondary_assistant_contact", StringType(), required=False),
    NestedField(23, "tracking_id", StringType(), required=False),
    NestedField(24, "tracking_url", StringType(), required=False),
    NestedField(25, "courier_name", StringType(), required=False),
    NestedField(26, "dimension_length", IntegerType(), required=False),
    NestedField(27, "dimension_height", IntegerType(), required=False),
    NestedField(28, "dimension_width", IntegerType(), required=False),
    NestedField(29, "dimension_units", StringType(), required=False),
    NestedField(30, "permit", StringType(), required=False),
    NestedField(31, "created_at", TimestampType(), required=True),
    NestedField(32, "updated_at", TimestampType(), required=False),
    NestedField(33, "createdAt", TimestampType(), required=True),
    NestedField(34, "updatedAt", TimestampType(), required=False),
    NestedField(35, "created_by", StringType(), required=False),
    NestedField(36, "updated_by", StringType(), required=False),
    NestedField(37, "courier_code", StringType(), required=False),
    NestedField(38, "ewaybillno", StringType(), required=False),
    NestedField(39, "ewaybilldate", TimestampType(), required=False),
    NestedField(40, "tracking_ref_suffix", StringType(), required=False),


]

uploadloggers = [
    NestedField(1, "time_sorted_id", StringType(), required=True),
    NestedField(2, "id", IntegerType(), required=True),
    NestedField(3, "order_type", StringType(), required=False),
    NestedField(4, "upload_url", StringType(), required=False),
    NestedField(5, "upload_filename", StringType(), required=False),
    NestedField(6, "additional_data", StringType(), required=False),
    NestedField(7, "logged_in", StringType(), required=False),
    NestedField(8, "created_at", TimestampType(), required=True),
    NestedField(9, "updated_at", TimestampType(), required=False),
    NestedField(10, "created_by", StringType(), required=False),
    NestedField(11, "updated_by", StringType(), required=False),

]

users = [
    NestedField(1, "id", StringType(), required=True),
    NestedField(2, "time_sorted_id", StringType(), required=True),
    NestedField(3, "email", StringType(), required=False),
    NestedField(4, "email_verified", BooleanType(), required=False),
    NestedField(5, "firstname", StringType(), required=True),
    NestedField(6, "lastname", StringType(), required=False),
    NestedField(7, "password", StringType(), required=True),
    NestedField(8, "role", StringType(), required=False),
    NestedField(9, "location_type", StringType(), required=True),
    NestedField(10, "warehouse", StringType(), required=False),
    NestedField(11, "store", StringType(), required=False),
    NestedField(12, "isActive", BooleanType(), required=True),
    NestedField(13, "other_data", StringType(), required=False),
    NestedField(14, "picture", StringType(), required=False),
    NestedField(15, "branch_code_list", StringType(), required=False),
    NestedField(16, "branch_list", StringType(), required=False),
    NestedField(17, "mobile_no", StringType(), required=False),
    NestedField(18, "created_by", StringType(), required=False),
    NestedField(19, "updated_by", StringType(), required=False),
    NestedField(20, "created_at", TimestampType(), required=True),
    NestedField(21, "updated_at", TimestampType(), required=False),
    NestedField(22, "createdAt", TimestampType(), required=True),
    NestedField(23, "updatedAt", TimestampType(), required=True),
    NestedField(24, "created_on", TimestampType(), required=True),
    NestedField(25, "updated_on", TimestampType(), required=False),


]

vehicles = [
    NestedField(1, "id", StringType(), required=True),
    NestedField(2, "time_sorted_id", StringType(), required=True),
    NestedField(3, "type_of_vehicle", StringType(), required=True),
    NestedField(4, "truck_name", StringType(), required=True),
    NestedField(5, "truck_reg_no", StringType(), required=True),
    NestedField(6, "capacity", StringType(), required=True),
    NestedField(7, "ratings", StringType(), required=False),
    NestedField(8, "is_available", BooleanType(), required=False),
    NestedField(9, "vehicle_from", StringType(), required=True),
    NestedField(10, "engine_type", StringType(), required=True),
    NestedField(11, "vehicle_image", StringType(), required=False),
    NestedField(12, "created_at", TimestampType(), required=True),
    NestedField(13, "updated_at", TimestampType(), required=False),
    NestedField(14, "created_by", StringType(), required=False),
    NestedField(15, "updated_by", StringType(), required=False),
    NestedField(16, "documents", StringType(), required=False),
    NestedField(17, "default_driver_name", StringType(), required=False),
    NestedField(18, "default_driver_id", StringType(), required=False),
    NestedField(19, "createdAt", TimestampType(), required=True),
    NestedField(20, "updatedAt", TimestampType(), required=False),
    NestedField(21, "branch_code_list", StringType(), required=False),


]
