from dataclasses import fields

from pyarrow import Schema
from pyiceberg.types import LongType, StringType, DateType, DoubleType, NestedField, TimestampType, BooleanType, \
    IntegerType, FloatType


MasterSchema = [
    NestedField(1,"order_id",StringType(),required=True),
    NestedField(2, "sale_order_id", StringType(),required=True),
    NestedField(3, "invoice_no", StringType()),
    NestedField(4, "invoice_date", TimestampType()),
    NestedField(5, "invoice_reff_no", StringType()),
    NestedField(6, "invoice_reff_date", StringType()),
    NestedField(7, "channel", StringType()),
    NestedField(8, "channel_medium", StringType()),
    NestedField(9, "order_status", StringType()),
    NestedField(10, "order_tag", StringType()),
    NestedField(11, "order_inv_status", StringType()),
    NestedField(12, "order_type", StringType()),
    NestedField(13, "delivery_from", StringType()),
    NestedField(14, "delivery_from_branchcode", StringType()),
    NestedField(15, "billing_branch_code", StringType()),
    NestedField(16, "cust_id", StringType()),
    NestedField(17, "cust_primary_email", StringType()),
    NestedField(18, "cust_primary_contact", StringType()),
    NestedField(19, "cust_mobile", StringType()),
    NestedField(20, "customer_address", StringType()),
    NestedField(21, "shipment_address", StringType()),
    NestedField(22, "latitude", FloatType()),
    NestedField(23, "longitude", FloatType()),
    NestedField(24, "billing_address", StringType()),
    NestedField(25, "payment_details", StringType()),
    NestedField(26, "refund_details", StringType()),
    NestedField(27, "voucher_details", StringType()),
    NestedField(28, "employee_sale_details", StringType()),
    NestedField(29, "order_summary_details", StringType()),
    NestedField(30, "other_details", StringType()),
    NestedField(31, "service_details", StringType()),
    NestedField(32, "invoice_pdf", StringType()),
    NestedField(33, "lineitems", StringType()),
    NestedField(34, "lineitem_status", StringType()),
    NestedField(35, "created_at", TimestampType()),
    NestedField(36, "created_by", StringType()),
    NestedField(37, "updated_by", StringType()),
    NestedField(38, "updated_at", TimestampType()),
    NestedField(39, "oms_data_migration_status", IntegerType()),
    NestedField(40, "cust_id_update", IntegerType()),
    NestedField(41, "multi_invoice", StringType()),
    NestedField(42, "updated_at_new", TimestampType())
]

Pickup_delivery_items = [
    NestedField(1, "pickup_delivery_req_item_id", StringType()),
    NestedField(2, "pickup_delivery_req_id", StringType()),
    NestedField(3, "order_id", StringType()),
    NestedField(4, "sale_order_id", StringType()),
    NestedField(5, "invoice_no", StringType()),
    NestedField(6, "invoice_date", TimestampType()),
    NestedField(7, "invoice_reff_no", StringType()),
    NestedField(8, "invoice_reff_date", StringType()),
    NestedField(9, "expect_delivery_pickup_dt", TimestampType()),
    NestedField(10, "customer_status", StringType()),
    NestedField(11, "internal_status", StringType()),
    NestedField(12, "inventory_status", StringType()),
    NestedField(13, "shipment_status", StringType()),
    NestedField(14, "inward_exchange_status", StringType()),
    NestedField(15, "inventory_location_code", StringType()),
    NestedField(16, "docking_area", StringType()),
    NestedField(17, "docking_area_code", StringType()),
    NestedField(18, "type_of_order", StringType()),
    NestedField(19, "item_code", StringType()),
    NestedField(20, "item_name", StringType()),
    NestedField(21, "item_image", StringType()),
    NestedField(22, "item_weight", StringType()),
    NestedField(23, "item_qty", StringType()),
    NestedField(24, "category_code", StringType()),
    NestedField(25, "category_name", StringType()),
    NestedField(26, "inventory_location", StringType()),
    NestedField(27, "inventory_location_branchname", StringType()),
    NestedField(28, "inventory_location_mobileno", StringType()),
    NestedField(29, "order_type", StringType()),
    NestedField(30, "order_line_item_id", StringType()),
    NestedField(31, "picklist_id", StringType()),
    NestedField(32, "picker_id", StringType()),
    NestedField(33, "picker_details", StringType()),
    NestedField(34, "picker_added_dt", TimestampType()),
    NestedField(35, "manifest_id", StringType()),
    NestedField(36, "manifest_added_dt", TimestampType()),
    NestedField(37, "shipment_id", StringType()),
    NestedField(38, "driver_code", StringType()),
    NestedField(39, "driver_name", StringType()),
    NestedField(40, "driver_image", StringType()),
    NestedField(41, "driver_contact", StringType()),
    NestedField(42, "assistant_code", StringType()),
    NestedField(43, "assistant_name", StringType()),
    NestedField(44, "assistant_pic", StringType()),
    NestedField(45, "assistant_contact", StringType()),
    NestedField(46, "vehicle_no", StringType()),
    NestedField(47, "vehicle_type", StringType()),
    NestedField(48, "vehicle_name", StringType()),
    NestedField(49, "vehicle_image", StringType()),
    NestedField(50, "order_tag", StringType()),
    NestedField(51, "order_inv_status", StringType()),
    NestedField(52, "tracking_id", StringType()),
    NestedField(53, "tracking_url", StringType()),
    NestedField(54, "permit", StringType()),
    NestedField(55, "courier_name", StringType()),
    NestedField(56, "courier_details", StringType()),
    NestedField(57, "ispickup_active", IntegerType()),
    NestedField(58, "dimension_length", IntegerType()),
    NestedField(59, "dimension_height", IntegerType()),
    NestedField(60, "dimension_width", IntegerType()),
    NestedField(61, "dimension_units", StringType()),
    NestedField(62, "latitude", FloatType()),
    NestedField(63, "longitude", FloatType()),
    NestedField(64, "inventory_location_address", StringType()),
    NestedField(65, "status_notification", StringType()),
    NestedField(66, "item_price", StringType()),
    NestedField(67, "item_qty_label", StringType()),
    NestedField(68, "item_dimension", StringType()),
    NestedField(69, "line_itemid", StringType()),
    NestedField(70, "invoice_status", StringType()),
    NestedField(71, "exchange_invo_no", TimestampType()),
    NestedField(72, "exchange_invo_date", StringType()),
    NestedField(73, "exchange_invoice_url", StringType()),
    NestedField(74, "exchange_collected_amount", StringType()),
    NestedField(75, "brand", StringType()),
    NestedField(76, "capture_do_url", StringType()),
    NestedField(77, "shipment_tracking_id", StringType()),
    NestedField(78, "shipping_label_url", StringType()),
    NestedField(79, "reattempt_count", IntegerType()),
    NestedField(80, "secondary_assistant_code", StringType()),
    NestedField(81, "secondary_assistant_name", StringType()),
    NestedField(82, "secondary_assistant_pic", StringType()),
    NestedField(83, "secondary_assistant_contact", StringType()),
    NestedField(84, "pickup_label_id", StringType()),
    NestedField(85, "collection_location_type", StringType()),
    NestedField(86, "collection_location_code", StringType()),
    NestedField(87, "collection_location_branchname", StringType()),
    NestedField(88, "collection_location_address", StringType()),
    NestedField(89, "collection_location_mobileno", StringType()),
    NestedField(90, "collection_docking_area", StringType()),
    NestedField(91, "collection_docking_area_code", StringType()),
    NestedField(92, "to_location_email", StringType()),
    NestedField(93, "to_location_mobileno", StringType()),
    NestedField(94, "to_location_address", StringType()),
    NestedField(95, "to_location_pincode", IntegerType()),
    NestedField(96, "to_location_lat_long", StringType()),
    NestedField(97, "shipment_transfer_info", StringType()),
    NestedField(98, "shipment_type", StringType()),
    NestedField(99, "home_pickup", StringType()),
    NestedField(100, "row_added_dt", TimestampType()),
    NestedField(101, "row_updated_dt", TimestampType()),
    NestedField(102, "row_added_by", StringType()),
    NestedField(103, "row_updated_by", StringType()),
    NestedField(104, "goods_received_date", TimestampType()),
    NestedField(105, "to_location_fullname", StringType()),
    NestedField(106, "courier_code", StringType()),
    NestedField(107, "billing_branch_code", StringType()),
    NestedField(108, "otp_verified_status", IntegerType()),
    NestedField(109, "item_serial_no", StringType()),
    NestedField(110, "payment_verification", IntegerType()),
    NestedField(111, "selling_price", StringType()),
    NestedField(112, "vendor_name", StringType()),
    NestedField(113, "vendor_id", StringType()),
    NestedField(114, "vendor_details", StringType()),
    NestedField(115, "is_item_installable", StringType()),
    NestedField(116, "sale_invoice_no", StringType()),
    NestedField(117, "sale_invoice_date", StringType()),
    NestedField(118, "dismantle_label", StringType()),
    NestedField(119, "quote_id", StringType()),
    NestedField(120, "billed_at_branch_name", StringType()),
    NestedField(121, "offer_type", StringType()),
    NestedField(122, "delivery_type", StringType()),
    NestedField(123, "delivery_charge", IntegerType()),
    NestedField(124, "oms_data_migration_status", StringType()),
    NestedField(125, "dropship_flag", IntegerType()),
    NestedField(126, "erp_po_createdAt", StringType()),
    NestedField(127, "erp_po_no", StringType()),
    NestedField(128, "seller_order_id", StringType()),
    NestedField(129, "seller_item_code", StringType()),
    NestedField(130, "seller_id", StringType()),
    NestedField(131, "seller_order_createdAt", StringType()),
    NestedField(132, "seller_apob_code", StringType()),
    NestedField(133, "unit_price", StringType()),
    NestedField(134, "discount_price", StringType()),
    NestedField(135, "plant", StringType()),
    NestedField(136, "seller_branch_code", StringType()),
    NestedField(137, "tracking_details", StringType()),
    NestedField(138, "invoiced_item_detail", StringType()),
    NestedField(139, "invoice_url", StringType()),
    NestedField(140, "updated_at_new", TimestampType()),
]

Status_event = [
    NestedField(1,"status_event_id",StringType()),
    NestedField(2,"type",StringType()),
    NestedField(3,"channel",StringType()),
    NestedField(4,"system",StringType()),
    NestedField(5,"medium",StringType()),
    NestedField(6,"flow",StringType()),
    NestedField(7,"order_id",StringType()),
    NestedField(8,"inventory_status",StringType()),
    NestedField(9,"shipment_status",StringType()),
    NestedField(10,"internal_status",StringType()),
    NestedField(11,"customer_status",StringType()),
    NestedField(12,"latitude",FloatType()),
    NestedField(13,"longitude",FloatType()),
    NestedField(14,"from_location_code",StringType()),
    NestedField(15,"to_location_code",StringType()),
    NestedField(16,"pickup_delivery_req_item_id",StringType()),
    NestedField(17,"intransit_pickup_delivery_req_item_id",StringType()),
    NestedField(18,"line_item_id",StringType()),
    NestedField(19,"manifest_id",StringType()),
    NestedField(20,"shipment_id",StringType()),
    NestedField(21,"item_code",StringType()),
    NestedField(22,"invoice_no",StringType()),
    NestedField(23,"invoice_date",TimestampType()),
    NestedField(24,"exp_delivery_date",TimestampType()),
    NestedField(25,"picklist_id",StringType()),
    NestedField(26,"wh_st_empid",StringType()),
    NestedField(27,"wh_st_empname", StringType()),
    NestedField(28,"driver_code",StringType()),
    NestedField(29,"driver_name",StringType()),
    NestedField(30,"driver_emp_id",StringType()),
    NestedField(31,"driver_contact",StringType()),
    NestedField(32,"ass_code",StringType()),
    NestedField(33,"ass_name",StringType()),
    NestedField(34,"ass_emp_id",StringType()),
    NestedField(35,"ass_contact",StringType()),
    NestedField(36,"sec_ass_code",StringType()),
    NestedField(37,"sec_ass_name",StringType()),
    NestedField(38,"sec_emp_id",StringType()),
    NestedField(39,"sec_contact",StringType()),
    NestedField(40,"vehicle_no",StringType()),
    NestedField(41,"vehicle_name",StringType()),
    NestedField(42,"docking_area",StringType()),
    NestedField(43,"type_of_order",StringType()),
    NestedField(44,"cust_name",StringType()),
    NestedField(45,"cust_mobile_num",StringType()),
    NestedField(46,"imei",StringType()),
    NestedField(47,"tracking_id",StringType()),
    NestedField(48,"comments",StringType()),
    NestedField(49,"courier_name",StringType()),
    NestedField(50,"action",StringType()),
    NestedField(51,"module_name",StringType()),
    NestedField(52,"notification_status",StringType()),
    NestedField(53,"order_inv_status",StringType()),
    NestedField(54,"additional_info",StringType()),
    NestedField(55,"row_added_by",StringType()),
    NestedField(56,"row_added_empid",StringType()),
    NestedField(57,"row_added_dttm",TimestampType()),
    NestedField(58,"shipment_tracking_id",StringType()),
    NestedField(59,"row_updated_dttm",TimestampType()),
    NestedField(60,"oms_data_migration_status",StringType()),
    NestedField(61,"updated_at_new",TimestampType()),

]

OrderLineItems = [
    NestedField(1,"line_item_id",StringType()),
    NestedField(2,"order_line_item_id",StringType()),
    NestedField(3,"master_order_id",StringType()),
    NestedField(4,"master_sale_order_id",StringType()),
    NestedField(5,"delivery_from",StringType()),
    NestedField(6,"customer_status",StringType()),
    NestedField(7,"inventory_status",StringType()),
    NestedField(8,"internal_status",StringType()),
    NestedField(9,"shipping_status",StringType()),
    NestedField(10,"category_code",StringType()),
    NestedField(11,"category_name",StringType()),
    NestedField(12,"item_qty_label",StringType()),
    NestedField(13,"exg_invo_no",StringType()),
    NestedField(14,"exg_invo_date",StringType()),
    NestedField(15,"home_pickup",StringType()),
    NestedField(16,"order_inv_status",StringType()),
    NestedField(17,"slug",StringType()),
    NestedField(18,"product_name",StringType()),
    NestedField(19,"model",StringType()),
    NestedField(20,"erp_item_code",StringType()),
    NestedField(21,"quantity",IntegerType()),
    NestedField(22,"type_of_order",StringType()),
    NestedField(23,"product_hsn",StringType()),
    NestedField(24,"image",StringType()),
    NestedField(25,"options",StringType()),
    NestedField(26,"delivery_charges",StringType()),
    NestedField(27,"price",StringType()),
    NestedField(28,"special_price",IntegerType()),
    NestedField(29,"brand_code",StringType()),
    NestedField(30,"brand_name",StringType()),
    NestedField(31,"product_policy",StringType()),
    NestedField(32,"billed_details",StringType()),
    NestedField(33,"delivery_details",StringType()),
    NestedField(34,"invoice_details",StringType()),
    NestedField(35,"tax_details",StringType()),
    NestedField(36,"insurance_details",StringType()),
    NestedField(37,"preorder_response",StringType()),
    NestedField(38,"seller_details",StringType()),
    NestedField(39,"shipment_details",StringType()),
    NestedField(40,"return_details",StringType()),
    NestedField(41,"return_refund_details",StringType()),
    NestedField(42,"return_replace_details",StringType()),
    NestedField(43,"return_exchange_details",StringType()),
    NestedField(44,"created_at",TimestampType()),
    NestedField(45,"updated_at",TimestampType()),
    NestedField(46,"created_by",StringType()),
    NestedField(47,"updated_by",StringType()),
    NestedField(48,"serial_no",StringType()),
    NestedField(49,"offer_type",StringType()),
    NestedField(50,"delivery_type",StringType()),
    NestedField(51,"oms_data_migration_status",IntegerType()),
    
]